# Generated by Django 6.0 on 2025-12-12 21:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HealthScreening",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "screening_type",
                    models.CharField(
                        choices=[
                            ("vision", "Vision Screening"),
                            ("hearing", "Hearing Screening"),
                            ("dental", "Dental Screening"),
                            ("bmi", "BMI/Height/Weight"),
                            ("blood_pressure", "Blood Pressure"),
                            ("general", "General Health Checkup"),
                            ("immunization", "Immunization Review"),
                            ("mental_health", "Mental Health Screening"),
                            ("postural", "Postural Screening"),
                            ("skin", "Skin Check"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="screening type",
                    ),
                ),
                ("screening_date", models.DateField(verbose_name="screening date")),
                (
                    "screening_result",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("abnormal", "Abnormal"),
                            ("needs_attention", "Needs Attention"),
                            ("referral_required", "Referral Required"),
                            ("pending", "Pending Results"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="screening result",
                    ),
                ),
                (
                    "result_details",
                    models.TextField(blank=True, verbose_name="result details"),
                ),
                (
                    "measurements",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Store measurement data as key-value pairs",
                        verbose_name="measurements",
                    ),
                ),
                (
                    "recommendations",
                    models.TextField(blank=True, verbose_name="recommendations"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="follow up required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow up date"
                    ),
                ),
                (
                    "referral_made",
                    models.BooleanField(default=False, verbose_name="referral made"),
                ),
                (
                    "referral_details",
                    models.TextField(blank=True, verbose_name="referral details"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="additional notes"),
                ),
                (
                    "parent_notified",
                    models.BooleanField(default=False, verbose_name="parent notified"),
                ),
                (
                    "notification_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="notification date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Screening",
                "verbose_name_plural": "Health Screenings",
                "ordering": ["-screening_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="MedicalAppointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("checkup", "Regular Checkup"),
                            ("illness", "Illness/Injury"),
                            ("dental", "Dental"),
                            ("vision", "Vision"),
                            ("mental_health", "Mental Health"),
                            ("specialist", "Specialist Consultation"),
                            ("emergency", "Emergency"),
                            ("follow_up", "Follow-up"),
                            ("screening", "Health Screening"),
                            ("other", "Other"),
                        ],
                        default="checkup",
                        max_length=20,
                        verbose_name="appointment type",
                    ),
                ),
                (
                    "appointment_status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="appointment status",
                    ),
                ),
                ("appointment_date", models.DateField(verbose_name="appointment date")),
                ("appointment_time", models.TimeField(verbose_name="appointment time")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=30,
                        validators=[
                            django.core.validators.MinValueValidator(15),
                            django.core.validators.MaxValueValidator(480),
                        ],
                        verbose_name="duration (minutes)",
                    ),
                ),
                (
                    "healthcare_provider",
                    models.CharField(
                        max_length=100, verbose_name="healthcare provider"
                    ),
                ),
                (
                    "provider_specialty",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="provider specialty"
                    ),
                ),
                (
                    "provider_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="provider contact"
                    ),
                ),
                (
                    "clinic_hospital_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="clinic/hospital name"
                    ),
                ),
                ("reason_for_visit", models.TextField(verbose_name="reason for visit")),
                ("symptoms", models.TextField(blank=True, verbose_name="symptoms")),
                ("diagnosis", models.TextField(blank=True, verbose_name="diagnosis")),
                (
                    "treatment_provided",
                    models.TextField(blank=True, verbose_name="treatment provided"),
                ),
                (
                    "prescriptions",
                    models.TextField(blank=True, verbose_name="prescriptions"),
                ),
                (
                    "follow_up_required",
                    models.BooleanField(
                        default=False, verbose_name="follow up required"
                    ),
                ),
                (
                    "follow_up_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="follow up date"
                    ),
                ),
                (
                    "follow_up_notes",
                    models.TextField(blank=True, verbose_name="follow up notes"),
                ),
                (
                    "accompanied_by",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="accompanied by"
                    ),
                ),
                (
                    "parent_notified",
                    models.BooleanField(default=False, verbose_name="parent notified"),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="consultation fee",
                    ),
                ),
                (
                    "insurance_coverage",
                    models.BooleanField(
                        default=False, verbose_name="insurance coverage"
                    ),
                ),
                (
                    "out_of_pocket_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="out of pocket cost",
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Appointment",
                "verbose_name_plural": "Medical Appointments",
                "ordering": ["-appointment_date", "-appointment_time"],
            },
        ),
        migrations.CreateModel(
            name="Medication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "medication_name",
                    models.CharField(max_length=100, verbose_name="medication name"),
                ),
                (
                    "generic_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="generic name"
                    ),
                ),
                (
                    "medication_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Prescription"),
                            ("otc", "Over-the-Counter"),
                            ("supplement", "Supplement"),
                            ("topical", "Topical"),
                            ("inhaler", "Inhaler"),
                        ],
                        default="prescription",
                        max_length=20,
                        verbose_name="medication type",
                    ),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("liquid", "Liquid/Syrup"),
                            ("injection", "Injection"),
                            ("cream", "Cream/Ointment"),
                            ("drops", "Eye/Ear Drops"),
                            ("inhaler", "Inhaler"),
                            ("patch", "Patch"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=20,
                        verbose_name="dosage form",
                    ),
                ),
                (
                    "dosage_amount",
                    models.CharField(max_length=50, verbose_name="dosage amount"),
                ),
                (
                    "dosage_frequency",
                    models.CharField(max_length=100, verbose_name="dosage frequency"),
                ),
                (
                    "dosage_instructions",
                    models.TextField(blank=True, verbose_name="dosage instructions"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "administration_times",
                    models.JSONField(
                        default=list,
                        help_text="List of times when medication should be administered",
                        verbose_name="administration times",
                    ),
                ),
                (
                    "prescribed_by",
                    models.CharField(max_length=100, verbose_name="prescribed by"),
                ),
                (
                    "prescription_date",
                    models.DateField(verbose_name="prescription date"),
                ),
                (
                    "prescription_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="prescription number"
                    ),
                ),
                (
                    "administration_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("administered", "Administered"),
                            ("refused", "Refused"),
                            ("missed", "Missed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="administration status",
                    ),
                ),
                (
                    "administration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="administration date"
                    ),
                ),
                (
                    "administration_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="administration time"
                    ),
                ),
                (
                    "administration_notes",
                    models.TextField(blank=True, verbose_name="administration notes"),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, verbose_name="side effects"),
                ),
                (
                    "effectiveness_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rate effectiveness from 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="effectiveness rating",
                    ),
                ),
                (
                    "requires_refrigeration",
                    models.BooleanField(
                        default=False, verbose_name="requires refrigeration"
                    ),
                ),
                (
                    "emergency_medication",
                    models.BooleanField(
                        default=False, verbose_name="emergency medication"
                    ),
                ),
                (
                    "self_administered",
                    models.BooleanField(
                        default=False, verbose_name="self-administered"
                    ),
                ),
            ],
            options={
                "verbose_name": "Medication",
                "verbose_name_plural": "Medications",
                "ordering": ["-start_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="full name"),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("grandparent", "Grandparent"),
                            ("sibling", "Sibling"),
                            ("relative", "Relative"),
                            ("friend", "Friend"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="relationship",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                        ],
                        default="secondary",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "phone_primary",
                    models.CharField(max_length=20, verbose_name="primary phone"),
                ),
                (
                    "phone_secondary",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="secondary phone"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="email"),
                ),
                ("address", models.TextField(blank=True, verbose_name="address")),
                (
                    "workplace",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="workplace"
                    ),
                ),
                (
                    "work_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="work phone"
                    ),
                ),
                (
                    "best_contact_time",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="best contact time"
                    ),
                ),
                (
                    "can_pickup_student",
                    models.BooleanField(
                        default=True, verbose_name="can pickup student"
                    ),
                ),
                (
                    "can_make_medical_decisions",
                    models.BooleanField(
                        default=False, verbose_name="can make medical decisions"
                    ),
                ),
                (
                    "can_access_records",
                    models.BooleanField(
                        default=False, verbose_name="can access medical records"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "last_contacted",
                    models.DateField(
                        blank=True, null=True, verbose_name="last contacted"
                    ),
                ),
                (
                    "contact_notes",
                    models.TextField(blank=True, verbose_name="contact notes"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to="academics.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "verbose_name_plural": "Emergency Contacts",
                "ordering": ["student", "priority", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="HealthRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("a+", "A+"),
                            ("a-", "A-"),
                            ("b+", "B+"),
                            ("b-", "B-"),
                            ("ab+", "AB+"),
                            ("ab-", "AB-"),
                            ("o+", "O+"),
                            ("o-", "O-"),
                        ],
                        max_length=3,
                        verbose_name="blood group",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(250),
                        ],
                        verbose_name="height (cm)",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(300),
                        ],
                        verbose_name="weight (kg)",
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="BMI",
                    ),
                ),
                ("allergies", models.TextField(blank=True, verbose_name="allergies")),
                (
                    "chronic_conditions",
                    models.TextField(blank=True, verbose_name="chronic conditions"),
                ),
                (
                    "medications",
                    models.TextField(blank=True, verbose_name="current medications"),
                ),
                (
                    "disabilities",
                    models.TextField(
                        blank=True, verbose_name="disabilities/special needs"
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="emergency contact name",
                    ),
                ),
                (
                    "emergency_contact_relationship",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="relationship"
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="emergency contact phone",
                    ),
                ),
                (
                    "emergency_contact_email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name="emergency contact email",
                    ),
                ),
                (
                    "has_insurance",
                    models.BooleanField(
                        default=False, verbose_name="has health insurance"
                    ),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="insurance provider"
                    ),
                ),
                (
                    "insurance_policy_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="policy number"
                    ),
                ),
                (
                    "insurance_expiry_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="insurance expiry date"
                    ),
                ),
                (
                    "immunization_record",
                    models.TextField(blank=True, verbose_name="immunization record"),
                ),
                (
                    "vaccination_status",
                    models.TextField(blank=True, verbose_name="vaccination status"),
                ),
                (
                    "current_health_status",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("critical", "Critical"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="current health status",
                    ),
                ),
                (
                    "last_checkup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last checkup date"
                    ),
                ),
                (
                    "next_checkup_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next checkup date"
                    ),
                ),
                (
                    "medical_notes",
                    models.TextField(blank=True, verbose_name="medical notes"),
                ),
                (
                    "dietary_restrictions",
                    models.TextField(blank=True, verbose_name="dietary restrictions"),
                ),
                (
                    "physical_restrictions",
                    models.TextField(blank=True, verbose_name="physical restrictions"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_record",
                        to="academics.student",
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Record",
                "verbose_name_plural": "Health Records",
                "ordering": ["student__student_id"],
            },
        ),
    ]
