# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("academics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("health", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="medication",
            name="administered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medication_administrations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="administered by",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="medication",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medications",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="medicalappointment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="medicalappointment",
            name="referred_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_referrals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="referred by",
            ),
        ),
        migrations.AddField(
            model_name="medicalappointment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_appointments",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="healthscreening",
            name="conducted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_screenings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="conducted by",
            ),
        ),
        migrations.AddField(
            model_name="healthscreening",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="healthscreening",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_screenings",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="healthrecord",
            name="student",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="health_record",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contacts",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["student", "start_date"], name="health_medi_student_37f1ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["administration_status", "start_date"],
                name="health_medi_adminis_d07e88_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medication",
            index=models.Index(
                fields=["medication_name", "student"],
                name="health_medi_medicat_697583_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalappointment",
            index=models.Index(
                fields=["student", "appointment_date"],
                name="health_medi_student_6b4021_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalappointment",
            index=models.Index(
                fields=["appointment_status", "appointment_date"],
                name="health_medi_appoint_ab0407_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicalappointment",
            index=models.Index(
                fields=["appointment_type", "student"],
                name="health_medi_appoint_7852e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthscreening",
            index=models.Index(
                fields=["student", "screening_date"],
                name="health_heal_student_d79c12_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthscreening",
            index=models.Index(
                fields=["screening_type", "screening_result"],
                name="health_heal_screeni_495c71_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthscreening",
            index=models.Index(
                fields=["screening_date", "follow_up_required"],
                name="health_heal_screeni_b051ba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["student", "priority"], name="health_emer_student_3157a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["student", "is_active"], name="health_emer_student_a0e0e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["relationship", "student"],
                name="health_emer_relatio_02453c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emergencycontact",
            unique_together={("student", "full_name", "relationship")},
        ),
    ]
