# Generated by Django 6.0 on 2025-12-14 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("assessment", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentrule",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="academic_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assigned_assignments",
                to="academics.class",
                verbose_name="class assigned",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="graded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="graded_submissions",
                to="academics.teacher",
                verbose_name="graded by",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="original_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resubmissions",
                to="assessment.assignment",
                verbose_name="original submission",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignment_submissions",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="assignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assignments",
                to="academics.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="academic_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exams",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attendance",
                to="assessment.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="examattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_attendance",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_questions",
                to="assessment.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="examtype",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="exams",
                to="assessment.examtype",
                verbose_name="exam type",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="gradingsystem",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="grade",
            name="grading_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grades",
                to="assessment.gradingsystem",
                verbose_name="grading system",
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="entered_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="entered_marks",
                to="academics.teacher",
                verbose_name="entered by",
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="assessment.exam",
                verbose_name="exam",
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="mark",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marks",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="examquestion",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_questions",
                to="assessment.question",
                verbose_name="question",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="academic_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="questionbank",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_banks",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="question_bank",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment.questionbank",
                verbose_name="question bank",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="questionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="assessment.question",
                verbose_name="question",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="academic_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_report_cards",
                to="academics.teacher",
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="assessment.examtype",
                verbose_name="exam type",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generated_report_cards",
                to="academics.teacher",
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_cards",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="academic_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="exam_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="assessment.examtype",
                verbose_name="exam type",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="results",
                to="assessment.grade",
                verbose_name="grade",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="promoted_to_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promoted_results",
                to="academics.class",
                verbose_name="promoted to class",
            ),
        ),
        migrations.AddField(
            model_name="result",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="results",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="reportcard",
            name="result",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_card",
                to="assessment.result",
                verbose_name="result",
            ),
        ),
        migrations.AddField(
            model_name="resultsubject",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subject_results",
                to="assessment.grade",
                verbose_name="grade",
            ),
        ),
        migrations.AddField(
            model_name="resultsubject",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="resultsubject",
            name="result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_marks",
                to="assessment.result",
                verbose_name="result",
            ),
        ),
        migrations.AddField(
            model_name="resultsubject",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="result_marks",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="exam_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_answers",
                to="assessment.examquestion",
                verbose_name="exam question",
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="studentanswer",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exam_answers",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject", "class_assigned"],
                name="assessment__subject_1f16ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject", "academic_class"],
                name="assessment__subject_9a9f1f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["due_date", "is_published"],
                name="assessment__due_dat_2f48a1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["teacher", "academic_session"],
                name="assessment__teacher_534323_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["assignment_type"], name="assessment__assignm_05f513_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["student", "submission_status"],
                name="assessment__student_ce112c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["submission_status", "graded_date"],
                name="assessment__submiss_90909e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["is_late_submission", "submission_date"],
                name="assessment__is_late_2b6e7d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["academic_class", "due_date"],
                name="assessment__academi_57f7cb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["subject", "teacher"], name="assessment__subject_abe14e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assignment",
            index=models.Index(
                fields=["student", "submission_date"],
                name="assessment__student_39c7e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="examattendance",
            index=models.Index(
                fields=["exam", "student"], name="assessment__exam_id_4cee62_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="examattendance",
            unique_together={("exam", "student")},
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["academic_class", "exam_date"],
                name="assessment__academi_a17ba6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["subject", "exam_type"], name="assessment__subject_b0cae3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="grade",
            unique_together={("grading_system", "grade")},
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(
                fields=["exam", "student"], name="assessment__exam_id_873ca4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="mark",
            index=models.Index(
                fields=["student", "exam"], name="assessment__student_95421d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mark",
            unique_together={("exam", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="examquestion",
            unique_together={("exam", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="questionoption",
            unique_together={("question", "order")},
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["student", "academic_class"],
                name="assessment__student_b2467b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="result",
            index=models.Index(
                fields=["academic_class", "exam_type", "rank"],
                name="assessment__academi_9a99bf_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="result",
            unique_together={("student", "academic_class", "exam_type")},
        ),
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student", "academic_class", "exam_type")},
        ),
        migrations.AlterUniqueTogether(
            name="resultsubject",
            unique_together={("result", "subject")},
        ),
        migrations.AlterUniqueTogether(
            name="studentanswer",
            unique_together={("exam_question", "student")},
        ),
    ]
