# Generated by Django 4.2.17 on 2026-02-18 19:38

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "expense_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="expense number",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("salaries", "Salaries"),
                            ("utilities", "Utilities"),
                            ("maintenance", "Maintenance"),
                            ("teaching_aids", "Teaching Aids"),
                            ("office_supplies", "Office Supplies"),
                            ("sports_equipment", "Sports Equipment"),
                            ("lab_equipment", "Laboratory Equipment"),
                            ("transport", "Transport"),
                            ("rent", "Rent"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=500, verbose_name="description"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                ("expense_date", models.DateField(verbose_name="expense date")),
                (
                    "vendor",
                    models.CharField(blank=True, max_length=200, verbose_name="vendor"),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="vendor invoice number"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("online", "Online Payment"),
                            ("mobile", "Mobile Payment"),
                            ("paystack", "Paystack"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeDiscount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="discount name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="discount code"
                    ),
                ),
                (
                    "discount_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed Amount"),
                            ("full_waiver", "Full Waiver"),
                        ],
                        default="percentage",
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scholarship", "Scholarship"),
                            ("sibling", "Sibling Discount"),
                            ("early_payment", "Early Payment Discount"),
                            ("staff", "Staff Discount"),
                            ("special_needs", "Special Needs"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="discount category",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="discount value",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="maximum discount amount",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "requirements",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="requirements"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Discount",
                "verbose_name_plural": "Fee Discounts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="fee structure name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="fee code"
                    ),
                ),
                (
                    "fee_type",
                    models.CharField(
                        choices=[
                            ("tuition", "Tuition Fee"),
                            ("transport", "Transport Fee"),
                            ("hostel", "Hostel Fee"),
                            ("library", "Library Fee"),
                            ("laboratory", "Laboratory Fee"),
                            ("examination", "Examination Fee"),
                            ("sports", "Sports Fee"),
                            ("development", "Development Fee"),
                            ("other", "Other Fee"),
                        ],
                        default="tuition",
                        max_length=20,
                        verbose_name="fee type",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("half_yearly", "Half Yearly"),
                            ("yearly", "Yearly"),
                            ("one_time", "One Time"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="billing cycle",
                    ),
                ),
                (
                    "due_day",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                        verbose_name="due day of month",
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(default=False, verbose_name="is optional"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                        verbose_name="tax rate (%)",
                    ),
                ),
                (
                    "late_fee_per_day",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="late fee per day",
                    ),
                ),
                (
                    "max_late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="maximum late fee",
                    ),
                ),
                (
                    "discount_eligible",
                    models.BooleanField(
                        default=False, verbose_name="discount eligible"
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "ordering": ["academic_session", "fee_type", "applicable_class"],
            },
        ),
        migrations.CreateModel(
            name="FinancialReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "report_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="report number",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("income_statement", "Income Statement"),
                            ("balance_sheet", "Balance Sheet"),
                            ("cash_flow", "Cash Flow Statement"),
                            ("fee_collection", "Fee Collection Report"),
                            ("expense_summary", "Expense Summary"),
                            ("outstanding_fees", "Outstanding Fees Report"),
                            ("student_ledger", "Student Ledger"),
                        ],
                        max_length=20,
                        verbose_name="report type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="report title"),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "report_data",
                    models.JSONField(default=dict, verbose_name="report data"),
                ),
                ("summary", models.TextField(blank=True, verbose_name="summary")),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Financial Report",
                "verbose_name_plural": "Financial Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="invoice number",
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(max_length=100, verbose_name="billing period"),
                ),
                ("issue_date", models.DateField(verbose_name="issue date")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("issued", "Issued"),
                            ("partial", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="subtotal",
                    ),
                ),
                (
                    "total_discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total discount",
                    ),
                ),
                (
                    "total_tax",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total tax",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="total amount",
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="amount paid",
                    ),
                ),
                (
                    "balance_due",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="balance due",
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="late fee",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "terms_and_conditions",
                    models.TextField(blank=True, verbose_name="terms and conditions"),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-issue_date", "invoice_number"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="unit price",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        verbose_name="tax rate (%)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="discount amount",
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="line total",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
            ],
            options={
                "verbose_name": "Invoice Item",
                "verbose_name_plural": "Invoice Items",
                "ordering": ["invoice", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "payment_number",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="payment number",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="amount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("cheque", "Cheque"),
                            ("bank_transfer", "Bank Transfer"),
                            ("credit_card", "Credit Card"),
                            ("debit_card", "Debit Card"),
                            ("online", "Online Payment"),
                            ("mobile", "Mobile Payment"),
                            ("paystack", "Paystack"),
                            ("other", "Other"),
                        ],
                        default="cash",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                ("payment_date", models.DateField(verbose_name="payment date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "reference_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference number"
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="bank name"
                    ),
                ),
                (
                    "cheque_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="cheque number"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction ID"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "receipt_issued",
                    models.BooleanField(default=False, verbose_name="receipt issued"),
                ),
                (
                    "paystack_payment_id",
                    models.CharField(
                        blank=True,
                        help_text="Paystack payment reference ID",
                        max_length=100,
                        verbose_name="Paystack Payment ID",
                    ),
                ),
                (
                    "paystack_transaction_reference",
                    models.CharField(
                        blank=True,
                        help_text="Paystack transaction reference",
                        max_length=100,
                        verbose_name="Paystack Transaction Reference",
                    ),
                ),
                (
                    "paystack_authorization_code",
                    models.CharField(
                        blank=True,
                        help_text="Paystack authorization code for future payments",
                        max_length=100,
                        verbose_name="Paystack Authorization Code",
                    ),
                ),
                (
                    "paystack_customer_email",
                    models.EmailField(
                        blank=True,
                        help_text="Customer email used for Paystack payment",
                        max_length=254,
                        verbose_name="Paystack Customer Email",
                    ),
                ),
                (
                    "paystack_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata from Paystack",
                        verbose_name="Paystack Metadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-payment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaystackPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "paystack_reference",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="Paystack Reference",
                    ),
                ),
                (
                    "paystack_transaction_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Paystack Transaction ID",
                    ),
                ),
                (
                    "paystack_access_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Paystack Access Code"
                    ),
                ),
                (
                    "paystack_authorization_url",
                    models.URLField(
                        blank=True, verbose_name="Paystack Authorization URL"
                    ),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="customer email"),
                ),
                (
                    "customer_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="customer name"
                    ),
                ),
                (
                    "customer_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="customer phone"
                    ),
                ),
                (
                    "paystack_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("abandoned", "Abandoned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Paystack Status",
                    ),
                ),
                (
                    "paystack_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paystack Amount",
                    ),
                ),
                (
                    "paystack_currency",
                    models.CharField(
                        default="NGN", max_length=3, verbose_name="Paystack Currency"
                    ),
                ),
                (
                    "paystack_fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Paystack Fees",
                    ),
                ),
                (
                    "paystack_fees_deducted",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Paystack Fees Deducted",
                    ),
                ),
                (
                    "paystack_amount_received",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Paystack Amount Received",
                    ),
                ),
                (
                    "authorization_code",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Authorization Code"
                    ),
                ),
                (
                    "authorization_channel",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Authorization Channel"
                    ),
                ),
                (
                    "authorization_bin",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Authorization BIN"
                    ),
                ),
                (
                    "authorization_last4",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Authorization Last 4"
                    ),
                ),
                (
                    "authorization_exp_month",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Authorization Exp Month"
                    ),
                ),
                (
                    "authorization_exp_year",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Authorization Exp Year"
                    ),
                ),
                (
                    "authorization_card_type",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Authorization Card Type",
                    ),
                ),
                (
                    "authorization_bank",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Authorization Bank"
                    ),
                ),
                (
                    "authorization_country_code",
                    models.CharField(
                        blank=True,
                        max_length=3,
                        verbose_name="Authorization Country Code",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="metadata"),
                ),
                (
                    "paystack_response",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Paystack Response"
                    ),
                ),
                (
                    "paystack_created_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paystack Created At"
                    ),
                ),
                (
                    "paystack_paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paystack Paid At"
                    ),
                ),
                (
                    "paystack_updated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Paystack Updated At"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paystack_details",
                        to="finance.payment",
                        verbose_name="payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paystack Payment",
                "verbose_name_plural": "Paystack Payments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaystackWebhookEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("charge.success", "Charge Success"),
                            ("charge.failed", "Charge Failed"),
                            ("charge.abandoned", "Charge Abandoned"),
                            ("transfer.success", "Transfer Success"),
                            ("transfer.failed", "Transfer Failed"),
                            ("customer.created", "Customer Created"),
                            ("invoice.created", "Invoice Created"),
                            ("invoice.payment_failed", "Invoice Payment Failed"),
                            ("invoice.updated", "Invoice Updated"),
                            ("invoice.archive", "Invoice Archive"),
                            ("subscription.create", "Subscription Create"),
                            ("subscription.disable", "Subscription Disable"),
                            ("subscription.enable", "Subscription Enable"),
                            ("subscription.update", "Subscription Update"),
                            ("plan.create", "Plan Create"),
                            ("plan.update", "Plan Update"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                        verbose_name="event type",
                    ),
                ),
                (
                    "event_data",
                    models.JSONField(default=dict, verbose_name="event data"),
                ),
                (
                    "event_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="event reference"
                    ),
                ),
                (
                    "event_timestamp",
                    models.DateTimeField(verbose_name="event timestamp"),
                ),
                (
                    "processed",
                    models.BooleanField(default=False, verbose_name="processed"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="processed at"
                    ),
                ),
                (
                    "processing_error",
                    models.TextField(blank=True, verbose_name="processing error"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paystack_webhooks",
                        to="finance.payment",
                        verbose_name="payment",
                    ),
                ),
                (
                    "paystack_payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="finance.paystackpayment",
                        verbose_name="paystack payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paystack Webhook Event",
                "verbose_name_plural": "Paystack Webhook Events",
                "ordering": ["-event_timestamp", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "payment_method_type",
                    models.CharField(
                        choices=[("card", "Card"), ("bank", "Bank Account")],
                        default="card",
                        max_length=10,
                        verbose_name="payment method type",
                    ),
                ),
                (
                    "paystack_authorization_code",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        verbose_name="Paystack Authorization Code",
                    ),
                ),
                (
                    "paystack_customer_code",
                    models.CharField(
                        max_length=100, verbose_name="Paystack Customer Code"
                    ),
                ),
                (
                    "card_bin",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Card BIN"
                    ),
                ),
                (
                    "last4",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Last 4 digits"
                    ),
                ),
                (
                    "exp_month",
                    models.CharField(
                        blank=True, max_length=2, verbose_name="Expiry Month"
                    ),
                ),
                (
                    "exp_year",
                    models.CharField(
                        blank=True, max_length=4, verbose_name="Expiry Year"
                    ),
                ),
                (
                    "card_type",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Card Type"
                    ),
                ),
                (
                    "bank",
                    models.CharField(blank=True, max_length=100, verbose_name="Bank"),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True, max_length=3, verbose_name="Country Code"
                    ),
                ),
                (
                    "channel",
                    models.CharField(blank=True, max_length=50, verbose_name="Channel"),
                ),
                (
                    "reusable",
                    models.BooleanField(default=True, verbose_name="Reusable"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Method"),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment Method",
                "verbose_name_plural": "Payment Methods",
                "ordering": ["-created_at"],
            },
        ),
    ]
