# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("finance", "0001_initial"),
        ("academics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentmethod",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_methods",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="finance.feestructure",
                verbose_name="fee structure",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_reports",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="applicable_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="academics.class",
                verbose_name="applicable class",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="feediscount",
            name="applicable_fee_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="finance.feestructure",
                verbose_name="applicable fee types",
            ),
        ),
        migrations.AddField(
            model_name="feediscount",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="paid by",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.fileattachment",
                verbose_name="receipt attachment",
            ),
        ),
        migrations.AddIndex(
            model_name="paystackwebhookevent",
            index=models.Index(
                fields=["event_type", "processed"],
                name="finance_pay_event_t_896ef5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paystackwebhookevent",
            index=models.Index(
                fields=["event_reference"], name="finance_pay_event_r_4b72e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paystackwebhookevent",
            index=models.Index(
                fields=["event_timestamp"], name="finance_pay_event_t_903cb7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paystackpayment",
            index=models.Index(
                fields=["paystack_reference"], name="finance_pay_paystac_98f394_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paystackpayment",
            index=models.Index(
                fields=["customer_email"], name="finance_pay_custome_7ce73c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paystackpayment",
            index=models.Index(
                fields=["paystack_status"], name="finance_pay_paystac_09142a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paystackpayment",
            index=models.Index(
                fields=["authorization_code"], name="finance_pay_authori_65bf36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["user", "is_default"], name="finance_pay_user_id_3268d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["paystack_authorization_code"],
                name="finance_pay_paystac_2aa300_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="paymentmethod",
            index=models.Index(
                fields=["paystack_customer_code"], name="finance_pay_paystac_2fb9d7_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="paymentmethod",
            unique_together={("user", "paystack_authorization_code")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "payment_date"],
                name="finance_pay_student_809d60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status"], name="finance_pay_invoice_80fc36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method", "status"],
                name="finance_pay_payment_d402f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["paystack_payment_id"], name="finance_pay_paystac_8e7508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["paystack_transaction_reference"],
                name="finance_pay_paystac_f8cdb7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "status"], name="finance_inv_student_96f21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "status"], name="finance_inv_due_dat_fb9ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["academic_session", "status"],
                name="finance_inv_academi_89bebb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["report_type", "academic_session"],
                name="finance_fin_report__da59bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["start_date", "end_date"], name="finance_fin_start_d_21c54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["academic_session", "fee_type"],
                name="finance_fee_academi_9f0ece_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["applicable_class", "billing_cycle"],
                name="finance_fee_applica_b8c806_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="feestructure",
            constraint=models.UniqueConstraint(
                fields=("academic_session", "fee_type", "applicable_class"),
                name="unique_fee_structure",
            ),
        ),
        migrations.AddIndex(
            model_name="feediscount",
            index=models.Index(
                fields=["category", "is_active"], name="finance_fee_categor_90ea5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feediscount",
            index=models.Index(
                fields=["start_date", "end_date"], name="finance_fee_start_d_a3db1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "expense_date"],
                name="finance_exp_categor_095875_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["expense_date", "status"], name="finance_exp_expense_dad241_idx"
            ),
        ),
    ]
