# Generated by Django 5.2.7 on 2025-11-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="paid_expenses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="paid by",
            ),
        ),
        migrations.AddField(
            model_name="expense",
            name="receipt_attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="academics.fileattachment",
                verbose_name="receipt attachment",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="applicable_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fee_structures",
                to="academics.class",
                verbose_name="applicable class",
            ),
        ),
        migrations.AddField(
            model_name="feediscount",
            name="applicable_fee_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="discounts",
                to="finance.feestructure",
                verbose_name="applicable fee types",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_reports",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="financialreport",
            name="generated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoice_items",
                to="finance.feestructure",
                verbose_name="fee structure",
            ),
        ),
        migrations.AddField(
            model_name="invoiceitem",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="finance.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="finance.invoice",
                verbose_name="invoice",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="received_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_payments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="received by",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["category", "expense_date"],
                name="finance_exp_categor_095875_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["expense_date", "status"], name="finance_exp_expense_dad241_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["academic_session", "fee_type"],
                name="finance_fee_academi_9f0ece_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="feestructure",
            index=models.Index(
                fields=["applicable_class", "billing_cycle"],
                name="finance_fee_applica_b8c806_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="feestructure",
            constraint=models.UniqueConstraint(
                fields=("academic_session", "fee_type", "applicable_class"),
                name="unique_fee_structure",
            ),
        ),
        migrations.AddIndex(
            model_name="feediscount",
            index=models.Index(
                fields=["category", "is_active"], name="finance_fee_categor_90ea5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="feediscount",
            index=models.Index(
                fields=["start_date", "end_date"], name="finance_fee_start_d_a3db1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["report_type", "academic_session"],
                name="finance_fin_report__da59bc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="financialreport",
            index=models.Index(
                fields=["start_date", "end_date"], name="finance_fin_start_d_21c54d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["student", "status"], name="finance_inv_student_96f21e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["due_date", "status"], name="finance_inv_due_dat_fb9ca1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["academic_session", "status"],
                name="finance_inv_academi_89bebb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["student", "payment_date"],
                name="finance_pay_student_809d60_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status"], name="finance_pay_invoice_80fc36_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["payment_method", "status"],
                name="finance_pay_payment_d402f0_idx",
            ),
        ),
    ]
