# Generated by Django 5.2.7 on 2026-02-17 12:24

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_remove_academicsession_end_date_after_start_date_and_more'),
        ('core', '0002_initial'),
        ('finance', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='status changed at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('payment_method_type', models.CharField(choices=[('card', 'Card'), ('bank', 'Bank Account')], default='card', max_length=10, verbose_name='payment method type')),
                ('paystack_authorization_code', models.CharField(max_length=100, unique=True, verbose_name='Paystack Authorization Code')),
                ('paystack_customer_code', models.CharField(max_length=100, verbose_name='Paystack Customer Code')),
                ('card_bin', models.CharField(blank=True, max_length=20, verbose_name='Card BIN')),
                ('last4', models.CharField(blank=True, max_length=10, verbose_name='Last 4 digits')),
                ('exp_month', models.CharField(blank=True, max_length=2, verbose_name='Expiry Month')),
                ('exp_year', models.CharField(blank=True, max_length=4, verbose_name='Expiry Year')),
                ('card_type', models.CharField(blank=True, max_length=50, verbose_name='Card Type')),
                ('bank', models.CharField(blank=True, max_length=100, verbose_name='Bank')),
                ('country_code', models.CharField(blank=True, max_length=3, verbose_name='Country Code')),
                ('channel', models.CharField(blank=True, max_length=50, verbose_name='Channel')),
                ('reusable', models.BooleanField(default=True, verbose_name='Reusable')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Method')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='status changed at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('paystack_reference', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Paystack Reference')),
                ('paystack_transaction_id', models.CharField(blank=True, max_length=100, verbose_name='Paystack Transaction ID')),
                ('paystack_access_code', models.CharField(blank=True, max_length=100, verbose_name='Paystack Access Code')),
                ('paystack_authorization_url', models.URLField(blank=True, verbose_name='Paystack Authorization URL')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='customer email')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='customer name')),
                ('customer_phone', models.CharField(blank=True, max_length=20, verbose_name='customer phone')),
                ('paystack_status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('abandoned', 'Abandoned'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Paystack Status')),
                ('paystack_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Paystack Amount')),
                ('paystack_currency', models.CharField(default='NGN', max_length=3, verbose_name='Paystack Currency')),
                ('paystack_fees', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Paystack Fees')),
                ('paystack_fees_deducted', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Paystack Fees Deducted')),
                ('paystack_amount_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Paystack Amount Received')),
                ('authorization_code', models.CharField(blank=True, max_length=100, verbose_name='Authorization Code')),
                ('authorization_channel', models.CharField(blank=True, max_length=50, verbose_name='Authorization Channel')),
                ('authorization_bin', models.CharField(blank=True, max_length=20, verbose_name='Authorization BIN')),
                ('authorization_last4', models.CharField(blank=True, max_length=10, verbose_name='Authorization Last 4')),
                ('authorization_exp_month', models.CharField(blank=True, max_length=2, verbose_name='Authorization Exp Month')),
                ('authorization_exp_year', models.CharField(blank=True, max_length=4, verbose_name='Authorization Exp Year')),
                ('authorization_card_type', models.CharField(blank=True, max_length=50, verbose_name='Authorization Card Type')),
                ('authorization_bank', models.CharField(blank=True, max_length=100, verbose_name='Authorization Bank')),
                ('authorization_country_code', models.CharField(blank=True, max_length=3, verbose_name='Authorization Country Code')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('paystack_response', models.JSONField(blank=True, default=dict, verbose_name='Paystack Response')),
                ('paystack_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Paystack Created At')),
                ('paystack_paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Paystack Paid At')),
                ('paystack_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Paystack Updated At')),
            ],
            options={
                'verbose_name': 'Paystack Payment',
                'verbose_name_plural': 'Paystack Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended'), ('archived', 'Archived')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('status_changed_at', models.DateTimeField(auto_now_add=True, verbose_name='status changed at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('event_type', models.CharField(choices=[('charge.success', 'Charge Success'), ('charge.failed', 'Charge Failed'), ('charge.abandoned', 'Charge Abandoned'), ('transfer.success', 'Transfer Success'), ('transfer.failed', 'Transfer Failed'), ('customer.created', 'Customer Created'), ('invoice.created', 'Invoice Created'), ('invoice.payment_failed', 'Invoice Payment Failed'), ('invoice.updated', 'Invoice Updated'), ('invoice.archive', 'Invoice Archive'), ('subscription.create', 'Subscription Create'), ('subscription.disable', 'Subscription Disable'), ('subscription.enable', 'Subscription Enable'), ('subscription.update', 'Subscription Update'), ('plan.create', 'Plan Create'), ('plan.update', 'Plan Update'), ('other', 'Other')], default='other', max_length=50, verbose_name='event type')),
                ('event_data', models.JSONField(default=dict, verbose_name='event data')),
                ('event_reference', models.CharField(blank=True, max_length=100, verbose_name='event reference')),
                ('event_timestamp', models.DateTimeField(verbose_name='event timestamp')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processed at')),
                ('processing_error', models.TextField(blank=True, verbose_name='processing error')),
            ],
            options={
                'verbose_name': 'Paystack Webhook Event',
                'verbose_name_plural': 'Paystack Webhook Events',
                'ordering': ['-event_timestamp', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_authorization_code',
            field=models.CharField(blank=True, help_text='Paystack authorization code for future payments', max_length=100, verbose_name='Paystack Authorization Code'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_customer_email',
            field=models.EmailField(blank=True, help_text='Customer email used for Paystack payment', max_length=254, verbose_name='Paystack Customer Email'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional metadata from Paystack', verbose_name='Paystack Metadata'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_payment_id',
            field=models.CharField(blank=True, help_text='Paystack payment reference ID', max_length=100, verbose_name='Paystack Payment ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='paystack_transaction_reference',
            field=models.CharField(blank=True, help_text='Paystack transaction reference', max_length=100, verbose_name='Paystack Transaction Reference'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('online', 'Online Payment'), ('mobile', 'Mobile Payment'), ('paystack', 'Paystack'), ('other', 'Other')], default='cash', max_length=20, verbose_name='payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('online', 'Online Payment'), ('mobile', 'Mobile Payment'), ('paystack', 'Paystack'), ('other', 'Other')], default='cash', max_length=20, verbose_name='payment method'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paystack_payment_id'], name='finance_pay_paystac_8e7508_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['paystack_transaction_reference'], name='finance_pay_paystac_f8cdb7_idx'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='core.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='institution',
            field=models.ForeignKey(help_text='Institution this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='paystackpayment',
            name='payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paystack_details', to='finance.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='paystackwebhookevent',
            name='institution',
            field=models.ForeignKey(help_text='Institution this record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_records', to='core.institution', verbose_name='institution'),
        ),
        migrations.AddField(
            model_name='paystackwebhookevent',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paystack_webhooks', to='finance.payment', verbose_name='payment'),
        ),
        migrations.AddField(
            model_name='paystackwebhookevent',
            name='paystack_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhooks', to='finance.paystackpayment', verbose_name='paystack payment'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['user', 'is_default'], name='finance_pay_user_id_3268d3_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['paystack_authorization_code'], name='finance_pay_paystac_2aa300_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmethod',
            index=models.Index(fields=['paystack_customer_code'], name='finance_pay_paystac_2fb9d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentmethod',
            unique_together={('user', 'paystack_authorization_code')},
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['paystack_reference'], name='finance_pay_paystac_98f394_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['customer_email'], name='finance_pay_custome_7ce73c_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['paystack_status'], name='finance_pay_paystac_09142a_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackpayment',
            index=models.Index(fields=['authorization_code'], name='finance_pay_authori_65bf36_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackwebhookevent',
            index=models.Index(fields=['event_type', 'processed'], name='finance_pay_event_t_896ef5_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackwebhookevent',
            index=models.Index(fields=['event_reference'], name='finance_pay_event_r_4b72e8_idx'),
        ),
        migrations.AddIndex(
            model_name='paystackwebhookevent',
            index=models.Index(fields=['event_timestamp'], name='finance_pay_event_t_903cb7_idx'),
        ),
    ]
