# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetable",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="shared_with_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other classes participating in this shared event",
                related_name="shared_timetable_events",
                to="academics.class",
                verbose_name="shared with classes",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
    ]
