# Generated by Django 5.2.7 on 2025-11-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="behaviorrecord",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_behavior_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="escalated to",
            ),
        ),
        migrations.AddField(
            model_name="careerguidance",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_guidance",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="attendanceschedule",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_schedules",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="class_enrolled",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_records",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="promoted_to_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="promotions_received",
                to="academics.class",
                verbose_name="promoted to class",
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="parent_material",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="academics.classmaterial",
                verbose_name="parent material",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="class_transfers",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="from_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_out",
                to="academics.class",
                verbose_name="from class",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="initiated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="initiated_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiated by",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="to_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfers_in",
                to="academics.class",
                verbose_name="to class",
            ),
        ),
        migrations.AddField(
            model_name="committeemeeting",
            name="committee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="meetings",
                to="academics.academicplanningcommittee",
                verbose_name="committee",
            ),
        ),
        migrations.AddField(
            model_name="counselingreferral",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_referrals",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="counselingsession",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_sessions",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="academicplanningcommittee",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committees",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="departmentbudget",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="department_budgets",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="departmentbudget",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budgets",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="class_enrolled",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="fileattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="file_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AddField(
            model_name="committeemeeting",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="committee_meetings",
                to="academics.fileattachment",
                verbose_name="attachments",
            ),
        ),
        migrations.AddField(
            model_name="gradelevel",
            name="next_level",
            field=models.ForeignKey(
                blank=True,
                help_text="The level students typically progress to after this one",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_levels",
                to="academics.gradelevel",
                verbose_name="next level",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="grade_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="classes",
                to="academics.gradelevel",
                verbose_name="grade level",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="parentguardian",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user account",
            ),
        ),
        migrations.AddField(
            model_name="schoolpolicy",
            name="academic_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_policies",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="schoolpolicy",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="policy_attachments",
                to="academics.fileattachment",
                verbose_name="attachments",
            ),
        ),
        migrations.AddField(
            model_name="schoolpolicy",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="school_policies",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user account",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="counselingsession",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_sessions",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="counselingreferral",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_referrals",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="classtransferhistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transfer_history",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="allowed_students",
            field=models.ManyToManyField(
                blank=True,
                related_name="allowed_materials",
                to="academics.student",
                verbose_name="allowed students",
            ),
        ),
        migrations.AddField(
            model_name="careerguidance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_guidance",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="behaviorrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="behavior_records",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="academicwarning",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_warnings",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="academicrecord",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="academic_records",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="studentparentrelationship",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_relationships",
                to="academics.parentguardian",
                verbose_name="parent/guardian",
            ),
        ),
        migrations.AddField(
            model_name="studentparentrelationship",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_relationships",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subjects",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="prerequisites",
            field=models.ManyToManyField(
                blank=True, to="academics.subject", verbose_name="prerequisites"
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="academicplanningcommittee",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="committees",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="class_assigned",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="academics.department",
                verbose_name="department",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user account",
            ),
        ),
        migrations.AddField(
            model_name="subjectassignment",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subject_assignments",
                to="academics.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AddField(
            model_name="departmentbudget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "user__user_roles__role__role_type__in": [
                        "principal",
                        "department_head",
                    ]
                },
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_approvals",
                to="academics.teacher",
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="departmentbudget",
            name="requested_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="budget_requests",
                to="academics.teacher",
                verbose_name="requested by",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="head_of_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="headed_departments",
                to="academics.teacher",
                verbose_name="head of department",
            ),
        ),
        migrations.AddField(
            model_name="counselingsession",
            name="counselor",
            field=models.ForeignKey(
                limit_choices_to={"user__user_roles__role__role_type": "counselor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_sessions",
                to="academics.teacher",
                verbose_name="counselor",
            ),
        ),
        migrations.AddField(
            model_name="counselingreferral",
            name="counselor",
            field=models.ForeignKey(
                limit_choices_to={"user__user_roles__role__role_type": "counselor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="counseling_referrals_made",
                to="academics.teacher",
                verbose_name="counselor",
            ),
        ),
        migrations.AddField(
            model_name="committeemeeting",
            name="absentees",
            field=models.ManyToManyField(
                blank=True,
                related_name="committee_absences",
                to="academics.teacher",
                verbose_name="absentees",
            ),
        ),
        migrations.AddField(
            model_name="committeemeeting",
            name="attendees",
            field=models.ManyToManyField(
                blank=True,
                related_name="committee_attendance",
                to="academics.teacher",
                verbose_name="attendees",
            ),
        ),
        migrations.AddField(
            model_name="classmaterial",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="materials",
                to="academics.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="class_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="academics.teacher",
                verbose_name="class teacher",
            ),
        ),
        migrations.AddField(
            model_name="careerguidance",
            name="counselor",
            field=models.ForeignKey(
                limit_choices_to={"user__user_roles__role__role_type": "counselor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="career_guidance_sessions",
                to="academics.teacher",
                verbose_name="counselor",
            ),
        ),
        migrations.AddField(
            model_name="behaviorrecord",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_incidents",
                to="academics.teacher",
                verbose_name="reported by",
            ),
        ),
        migrations.AddField(
            model_name="academicwarning",
            name="issued_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issued_warnings",
                to="academics.teacher",
                verbose_name="issued by",
            ),
        ),
        migrations.AddField(
            model_name="academicplanningcommittee",
            name="chairperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chaired_committees",
                to="academics.teacher",
                verbose_name="chairperson",
            ),
        ),
        migrations.AddField(
            model_name="academicplanningcommittee",
            name="members",
            field=models.ManyToManyField(
                blank=True,
                related_name="committee_memberships",
                to="academics.teacher",
                verbose_name="committee members",
            ),
        ),
        migrations.AddField(
            model_name="academicplanningcommittee",
            name="secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary_committees",
                to="academics.teacher",
                verbose_name="secretary",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="class_assigned",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetables",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="shared_with_classes",
            field=models.ManyToManyField(
                blank=True,
                help_text="Other classes participating in this shared event",
                related_name="shared_timetable_events",
                to="academics.class",
                verbose_name="shared with classes",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="timetable",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="timetable_entries",
                to="academics.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendanceschedule",
            unique_together={("class_assigned", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(
                fields=["education_stage", "code"],
                name="academics_g_educati_c5df28_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="gradelevel",
            index=models.Index(
                fields=["grade_type", "education_stage"],
                name="academics_g_grade_t_3c2896_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("date", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="parentguardian",
            index=models.Index(
                fields=["last_name", "first_name"],
                name="academics_p_last_na_ba79e5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parentguardian",
            index=models.Index(
                fields=["is_primary_contact"], name="academics_p_is_prim_9983bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schoolpolicy",
            index=models.Index(
                fields=["policy_type", "is_active"],
                name="academics_s_policy__0e98e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schoolpolicy",
            index=models.Index(
                fields=["academic_session", "department"],
                name="academics_s_academi_217377_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["student_id", "status"], name="academics_s_student_da91cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["admission_number"], name="academics_s_admissi_70a43d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="student",
            index=models.Index(
                fields=["user", "status"], name="academics_s_user_id_be7b59_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["student", "enrollment_status"],
                name="academics_e_student_b0091c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="enrollment",
            index=models.Index(
                fields=["class_enrolled", "academic_session"],
                name="academics_e_class_e_45ab45_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together={
                ("class_enrolled", "roll_number", "academic_session"),
                ("student", "academic_session"),
            },
        ),
        migrations.AddIndex(
            model_name="classtransferhistory",
            index=models.Index(
                fields=["student", "transfer_date"],
                name="academics_c_student_9005b6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classtransferhistory",
            index=models.Index(
                fields=["from_class", "to_class"], name="academics_c_from_cl_e6e774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["student", "achievement_type"],
                name="academics_a_student_b00372_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="achievement",
            index=models.Index(
                fields=["achievement_date", "achievement_level"],
                name="academics_a_achieve_4c9b9c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicrecord",
            index=models.Index(
                fields=["student", "academic_session"],
                name="academics_a_student_4770d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicrecord",
            index=models.Index(
                fields=["class_enrolled", "academic_session"],
                name="academics_a_class_e_e2b68a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="academicrecord",
            unique_together={("student", "class_enrolled", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="studentparentrelationship",
            index=models.Index(
                fields=["student", "relationship"],
                name="academics_s_student_9e5e1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentparentrelationship",
            index=models.Index(
                fields=["parent", "is_legal_guardian"],
                name="academics_s_parent__6fd316_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentparentrelationship",
            unique_together={("student", "parent")},
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["code", "is_active"], name="academics_s_code_5bcde8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["department", "subject_type"],
                name="academics_s_departm_d87c1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["teacher_id", "status"], name="academics_t_teacher_6c9b76_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teacher",
            index=models.Index(
                fields=["department", "teacher_type"],
                name="academics_t_departm_20fe2b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["teacher", "academic_session"],
                name="academics_s_teacher_b2a614_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="subjectassignment",
            index=models.Index(
                fields=["class_assigned", "subject"],
                name="academics_s_class_a_1c17a8_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="subjectassignment",
            unique_together={
                ("teacher", "subject", "class_assigned", "academic_session")
            },
        ),
        migrations.AddIndex(
            model_name="departmentbudget",
            index=models.Index(
                fields=["department", "academic_session"],
                name="academics_d_departm_dc2cd4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentbudget",
            index=models.Index(
                fields=["budget_category", "is_approved"],
                name="academics_d_budget__5236ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="departmentbudget",
            index=models.Index(
                fields=["is_active", "academic_session"],
                name="academics_d_is_acti_6d9ae4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["name", "code"], name="academics_d_name_b372a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["counselor", "scheduled_date"],
                name="academics_c_counsel_80a0a5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["student", "scheduled_date"],
                name="academics_c_student_7b3d8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["session_status", "scheduled_date"],
                name="academics_c_session_592df4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingsession",
            index=models.Index(
                fields=["session_type", "academic_session"],
                name="academics_c_session_8ec63d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingreferral",
            index=models.Index(
                fields=["student", "referral_date"],
                name="academics_c_student_98df90_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingreferral",
            index=models.Index(
                fields=["counselor", "referral_status"],
                name="academics_c_counsel_f0801b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="counselingreferral",
            index=models.Index(
                fields=["referral_type", "urgency_level"],
                name="academics_c_referra_c801ac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="committeemeeting",
            index=models.Index(
                fields=["committee", "meeting_date"],
                name="academics_c_committ_ce5be6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="committeemeeting",
            index=models.Index(
                fields=["meeting_status", "meeting_date"],
                name="academics_c_meeting_e9e10e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="committeemeeting",
            index=models.Index(
                fields=["meeting_type", "committee"],
                name="academics_c_meeting_b04794_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classmaterial",
            index=models.Index(
                fields=["subject", "class_assigned"],
                name="academics_c_subject_c5fd20_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classmaterial",
            index=models.Index(
                fields=["teacher", "publish_date"],
                name="academics_c_teacher_09fbe8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classmaterial",
            index=models.Index(
                fields=["material_type", "is_public"],
                name="academics_c_materia_b68737_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="classmaterial",
            index=models.Index(
                fields=["access_level", "expiry_date"],
                name="academics_c_access__7eca72_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["grade_level", "class_type"],
                name="academics_c_grade_l_7d3c9b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="class",
            index=models.Index(
                fields=["class_teacher", "academic_session"],
                name="academics_c_class_t_45382c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={("grade_level", "class_type", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="careerguidance",
            index=models.Index(
                fields=["student", "session_date"],
                name="academics_c_student_fd808e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="careerguidance",
            index=models.Index(
                fields=["counselor", "session_date"],
                name="academics_c_counsel_e0fd33_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="careerguidance",
            index=models.Index(
                fields=["guidance_type", "academic_session"],
                name="academics_c_guidanc_b29e9a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorrecord",
            index=models.Index(
                fields=["student", "behavior_type"],
                name="academics_b_student_41c158_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorrecord",
            index=models.Index(
                fields=["incident_date", "severity"],
                name="academics_b_inciden_e06a51_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorrecord",
            index=models.Index(
                fields=["incident_category", "is_resolved"],
                name="academics_b_inciden_458051_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorrecord",
            index=models.Index(
                fields=["reported_by", "incident_date"],
                name="academics_b_reporte_681a1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="behaviorrecord",
            index=models.Index(
                fields=["case_number"], name="academics_b_case_nu_061cc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicwarning",
            index=models.Index(
                fields=["student", "is_resolved"], name="academics_a_student_2d4cdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="academicwarning",
            index=models.Index(
                fields=["warning_type", "warning_level"],
                name="academics_a_warning_14c48a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicplanningcommittee",
            index=models.Index(
                fields=["committee_type", "is_active"],
                name="academics_a_committ_244ec8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicplanningcommittee",
            index=models.Index(
                fields=["department", "academic_session"],
                name="academics_a_departm_5bf262_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="academicplanningcommittee",
            index=models.Index(
                fields=["term_start_date", "term_end_date"],
                name="academics_a_term_st_9ed71c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["class_assigned", "academic_session"],
                name="academics_t_class_a_182dea_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["teacher", "academic_session"],
                name="academics_t_teacher_e98ef6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["room_number", "academic_session"],
                name="academics_t_room_nu_8e3b48_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["day_of_week", "period_type"],
                name="academics_t_day_of__386f03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["is_published", "academic_session"],
                name="academics_t_is_publ_0c7283_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["room_type", "is_room_available"],
                name="academics_t_room_ty_3fa8d7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timetable",
            index=models.Index(
                fields=["room_building", "room_floor"],
                name="academics_t_room_bu_c0f87b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timetable",
            unique_together={
                ("class_assigned", "day_of_week", "period_number", "academic_session"),
                ("room_number", "day_of_week", "period_number", "academic_session"),
                ("teacher", "day_of_week", "period_number", "academic_session"),
            },
        ),
    ]
