# Generated by Django 5.2.7 on 2026-02-17 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='academicsession',
            name='end_date_after_start_date',
        ),
        migrations.RemoveConstraint(
            model_name='academicsession',
            name='term_number_within_semesters_range',
        ),
    ]
