# Generated by Django 4.2.17 on 2026-02-18 19:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="emergency contact"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="institution name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        max_length=20,
                        unique=True,
                        verbose_name="institution code",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="short name"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("preschool", "Preschool"),
                            ("elementary", "Elementary School"),
                            ("middle_school", "Middle School"),
                            ("high_school", "High School"),
                            ("college", "College/University"),
                            ("vocational", "Vocational/Technical"),
                            ("special_education", "Special Education"),
                            ("international", "International School"),
                        ],
                        default="high_school",
                        max_length=20,
                        verbose_name="institution type",
                    ),
                ),
                (
                    "ownership_type",
                    models.CharField(
                        choices=[
                            ("public", "Public/Government"),
                            ("private", "Private"),
                            ("charter", "Charter"),
                            ("religious", "Religious"),
                            ("international", "International"),
                        ],
                        default="private",
                        max_length=20,
                        verbose_name="ownership type",
                    ),
                ),
                ("website", models.URLField(blank=True, verbose_name="website")),
                (
                    "established_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="established date"
                    ),
                ),
                (
                    "max_students",
                    models.PositiveIntegerField(
                        default=1000, verbose_name="maximum students"
                    ),
                ),
                (
                    "max_staff",
                    models.PositiveIntegerField(
                        default=100, verbose_name="maximum staff"
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC", max_length=50, verbose_name="timezone"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "allows_online_enrollment",
                    models.BooleanField(
                        default=True, verbose_name="allows online enrollment"
                    ),
                ),
                (
                    "requires_parent_approval",
                    models.BooleanField(
                        default=True, verbose_name="requires parent approval"
                    ),
                ),
                (
                    "database_schema",
                    models.CharField(
                        blank=True,
                        help_text="For multi-tenant database separation",
                        max_length=50,
                        verbose_name="database schema",
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True, max_length=100, unique=True, verbose_name="API key"
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "verbose_name_plural": "Institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("override_value", models.JSONField(verbose_name="override value")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Institution Configuration",
                "verbose_name_plural": "Institution Configurations",
                "ordering": [
                    "institution",
                    "system_config__config_type",
                    "system_config__key",
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        unique=True,
                        verbose_name="config key",
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="config value")),
                (
                    "config_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("academic", "Academic"),
                            ("finance", "Finance"),
                            ("communication", "Communication"),
                            ("security", "Security"),
                            ("ui", "User Interface"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="config type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=False, verbose_name="is public"),
                ),
                (
                    "is_encrypted",
                    models.BooleanField(default=False, verbose_name="is encrypted"),
                ),
                (
                    "allows_institution_override",
                    models.BooleanField(
                        default=True, verbose_name="allows institution override"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "ordering": ["config_type", "key"],
            },
        ),
        migrations.CreateModel(
            name="SequenceGenerator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "sequence_type",
                    models.CharField(
                        choices=[
                            ("student_id", "Student ID"),
                            ("employee_id", "Employee ID"),
                            ("invoice", "Invoice Number"),
                            ("receipt", "Receipt Number"),
                            ("library_book", "Library Book ID"),
                            ("transport_bus", "Transport Bus ID"),
                            ("staff_application", "Staff Application Number"),
                        ],
                        max_length=50,
                        unique=True,
                        verbose_name="sequence type",
                    ),
                ),
                (
                    "prefix",
                    models.CharField(blank=True, max_length=10, verbose_name="prefix"),
                ),
                (
                    "suffix",
                    models.CharField(blank=True, max_length=10, verbose_name="suffix"),
                ),
                (
                    "last_number",
                    models.PositiveIntegerField(default=0, verbose_name="last number"),
                ),
                (
                    "padding",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="number padding",
                    ),
                ),
                (
                    "reset_frequency",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("yearly", "Yearly"),
                            ("monthly", "Monthly"),
                            ("daily", "Daily"),
                        ],
                        default="never",
                        max_length=20,
                        verbose_name="reset frequency",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sequence Generator",
                "verbose_name_plural": "Sequence Generators",
            },
        ),
        migrations.CreateModel(
            name="InstitutionUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "date_joined",
                    models.DateField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier within this institution",
                        max_length=20,
                        verbose_name="employee/student ID",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary institution for this user",
                        verbose_name="is primary institution",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_memberships",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution User",
                "verbose_name_plural": "Institution Users",
                "ordering": ["-is_primary", "date_joined"],
            },
        ),
    ]
