# Generated by Django 5.2.7 on 2025-11-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_institutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="institutionconfig",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="institutionconfig",
            name="system_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_overrides",
                to="core.systemconfig",
                verbose_name="system configuration",
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["code", "status"], name="core_instit_code_700416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["institution_type", "ownership_type"],
                name="core_instit_institu_f57799_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["is_active"], name="core_instit_is_acti_2b71cd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutionconfig",
            unique_together={("institution", "system_config")},
        ),
    ]
