# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionuser",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_memberships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="institutionconfig",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="configurations",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="institutionconfig",
            name="system_config",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="institution_overrides",
                to="core.systemconfig",
                verbose_name="system configuration",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_institutions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created by",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users associated with this institution",
                related_name="institutions",
                through="core.InstitutionUser",
                to=settings.AUTH_USER_MODEL,
                verbose_name="users",
            ),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(
                fields=["user", "is_primary"], name="core_instit_user_id_94deca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institutionuser",
            index=models.Index(
                fields=["institution", "user"], name="core_instit_institu_7da89f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="institutionuser",
            unique_together={("user", "institution")},
        ),
        migrations.AlterUniqueTogether(
            name="institutionconfig",
            unique_together={("institution", "system_config")},
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["code", "status"], name="core_instit_code_700416_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["institution_type", "ownership_type"],
                name="core_instit_institu_f57799_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="institution",
            index=models.Index(
                fields=["is_active"], name="core_instit_is_acti_2b71cd_idx"
            ),
        ),
    ]
