# Generated by Django 4.2.17 on 2026-02-19 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="database_schema",
            field=models.CharField(
                blank=True,
                help_text="Database schema (unused for single-tenant deployment)",
                max_length=50,
                verbose_name="database schema",
            ),
        ),
    ]
