# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0002_initial"),
        ("transport", "0001_initial"),
        ("academics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="incidentreport",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_incidents",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reported by",
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="route_schedule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="incident_reports",
                to="transport.routeschedule",
                verbose_name="route schedule",
            ),
        ),
        migrations.AddField(
            model_name="incidentreport",
            name="students_affected",
            field=models.ManyToManyField(
                blank=True,
                related_name="transport_incidents",
                to="academics.student",
                verbose_name="students affected",
            ),
        ),
        migrations.AddField(
            model_name="fuelrecord",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="fuelrecord",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fuel_records",
                to="transport.vehicle",
                verbose_name="vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user account",
            ),
        ),
        migrations.AddField(
            model_name="attendant",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="attendant",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendant_profile",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user account",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["vehicle_type", "status"], name="transport_v_vehicle_d11d45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["insurance_expiry"], name="transport_v_insuran_1ec231_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(
                fields=["fitness_expiry"], name="transport_v_fitness_35c29c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportallocation",
            index=models.Index(
                fields=["student", "status"], name="transport_t_student_f4f0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="transportallocation",
            index=models.Index(
                fields=["route_schedule", "status"],
                name="transport_t_route_s_97e92c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="transportallocation",
            index=models.Index(
                fields=["start_date", "end_date"], name="transport_t_start_d_d7851b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routestop",
            index=models.Index(
                fields=["route", "sequence"], name="transport_r_route_i_61ee45_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routestop",
            unique_together={("route", "sequence")},
        ),
        migrations.AddIndex(
            model_name="routeschedule",
            index=models.Index(
                fields=["route", "academic_session"],
                name="transport_r_route_i_79e5a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="routeschedule",
            index=models.Index(
                fields=["vehicle", "status"], name="transport_r_vehicle_1ae38d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="routeschedule",
            index=models.Index(
                fields=["driver", "status"], name="transport_r_driver__a3c5ec_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="routeschedule",
            unique_together={("route", "vehicle", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="route",
            index=models.Index(
                fields=["code", "is_active"], name="transport_r_code_a8c2c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["vehicle", "date"], name="transport_m_vehicle_4bb69e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerecord",
            index=models.Index(
                fields=["maintenance_type", "date"],
                name="transport_m_mainten_993dd9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["incident_type", "severity"],
                name="transport_i_inciden_806f02_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="incidentreport",
            index=models.Index(
                fields=["date", "route_schedule"], name="transport_i_date_1072bb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="fuelrecord",
            index=models.Index(
                fields=["vehicle", "date"], name="transport_f_vehicle_07d50f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["license_expiry", "status"],
                name="transport_d_license_c83a45_idx",
            ),
        ),
    ]
