# Generated by Django 6.0 on 2025-12-12 21:15

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        help_text="Primary email address for communication",
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        help_text="Primary mobile number for SMS notifications",
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?1?\\d{9,15}$",
                            )
                        ],
                        verbose_name="mobile number",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user has verified their email address",
                        verbose_name="verified",
                    ),
                ),
                (
                    "email_verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="email verified at"
                    ),
                ),
                (
                    "verification_token",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="verification token"
                    ),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="last login IP"
                    ),
                ),
                (
                    "current_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="current login IP"
                    ),
                ),
                (
                    "login_count",
                    models.PositiveIntegerField(default=0, verbose_name="login count"),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("es", "Spanish"),
                            ("fr", "French"),
                            ("ar", "Arabic"),
                        ],
                        default="en",
                        help_text="Preferred language for the interface",
                        max_length=10,
                        verbose_name="language",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="User's preferred timezone",
                        max_length=50,
                        verbose_name="timezone",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="location"
                    ),
                ),
                (
                    "login_method",
                    models.CharField(
                        choices=[
                            ("password", "Password"),
                            ("sso", "Single Sign-On"),
                            ("token", "Token"),
                        ],
                        default="password",
                        max_length=20,
                        verbose_name="login method",
                    ),
                ),
                (
                    "was_successful",
                    models.BooleanField(default=True, verbose_name="was successful"),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="failure reason"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="session key"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Login History",
                "verbose_name_plural": "Login History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ParentStudentRelationship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="relationship type",
                    ),
                ),
                (
                    "is_primary_contact",
                    models.BooleanField(
                        default=False,
                        help_text="Designates the primary contact for the student",
                        verbose_name="is primary contact",
                    ),
                ),
                (
                    "can_pickup",
                    models.BooleanField(
                        default=True,
                        help_text="Can this person pickup the student from school?",
                        verbose_name="can pickup student",
                    ),
                ),
                (
                    "emergency_contact_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which to contact in emergencies (0 = first)",
                        verbose_name="emergency contact order",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        limit_choices_to={"user_roles__role__role_type": "parent"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="parent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_roles__role__role_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_relationships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="student",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent-Student Relationship",
                "verbose_name_plural": "Parent-Student Relationships",
                "ordering": ["emergency_contact_order", "relationship_type"],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "password_hash",
                    models.CharField(max_length=255, verbose_name="password hash"),
                ),
                (
                    "change_reason",
                    models.CharField(
                        choices=[
                            ("initial", "Initial Setup"),
                            ("regular", "Regular Change"),
                            ("compromise", "Suspected Compromise"),
                            ("reset", "Password Reset"),
                        ],
                        default="regular",
                        max_length=20,
                        verbose_name="change reason",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="changed_passwords",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="changed by",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Password History",
                "verbose_name_plural": "Password History",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="role name"
                    ),
                ),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("super_admin", "Super Administrator"),
                            ("admin", "Administrator"),
                            ("principal", "Principal"),
                            ("department_head", "Department Head"),
                            ("counselor", "School Counselor"),
                            ("teacher", "Teacher"),
                            ("student", "Student"),
                            ("parent", "Parent"),
                            ("accountant", "Accountant"),
                            ("librarian", "Librarian"),
                            ("driver", "Driver"),
                            ("support", "Support Staff"),
                            ("transport_manager", "Transport Manager"),
                            ("hostel_warden", "Hostel Warden"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="role type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_system_role",
                    models.BooleanField(default=False, verbose_name="is system role"),
                ),
                (
                    "hierarchy_level",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Higher number indicates higher authority (0 = lowest)",
                        verbose_name="hierarchy level",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="auth.permission",
                        verbose_name="permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ["-hierarchy_level", "name"],
            },
        ),
        migrations.CreateModel(
            name="StaffApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="nationality"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone number")),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="state/province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                (
                    "position_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="position type",
                    ),
                ),
                (
                    "expected_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="expected salary",
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        max_length=200, verbose_name="highest qualification"
                    ),
                ),
                (
                    "institution",
                    models.CharField(max_length=200, verbose_name="institution"),
                ),
                (
                    "year_graduated",
                    models.PositiveIntegerField(verbose_name="year graduated"),
                ),
                (
                    "years_of_experience",
                    models.PositiveIntegerField(
                        default=0, verbose_name="years of experience"
                    ),
                ),
                (
                    "previous_employer",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous employer"
                    ),
                ),
                (
                    "previous_position",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous position"
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        help_text="Upload your CV (PDF, DOC, DOCX)",
                        upload_to="staff_applications/cvs/%Y/%m/%d/",
                        verbose_name="curriculum vitae",
                    ),
                ),
                (
                    "cover_letter",
                    models.FileField(
                        blank=True,
                        help_text="Upload your cover letter (optional)",
                        upload_to="staff_applications/cover_letters/%Y/%m/%d/",
                        verbose_name="cover letter",
                    ),
                ),
                (
                    "certificates",
                    models.FileField(
                        blank=True,
                        help_text="Upload relevant certificates (optional)",
                        upload_to="staff_applications/certificates/%Y/%m/%d/",
                        verbose_name="certificates",
                    ),
                ),
                (
                    "reference1_name",
                    models.CharField(max_length=100, verbose_name="reference 1 name"),
                ),
                (
                    "reference1_position",
                    models.CharField(
                        max_length=100, verbose_name="reference 1 position"
                    ),
                ),
                (
                    "reference1_contact",
                    models.CharField(
                        max_length=100, verbose_name="reference 1 contact"
                    ),
                ),
                (
                    "reference2_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference 2 name"
                    ),
                ),
                (
                    "reference2_position",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference 2 position"
                    ),
                ),
                (
                    "reference2_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="reference 2 contact"
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("interview_scheduled", "Interview Scheduled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="application status",
                    ),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="application date"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="review notes"),
                ),
                (
                    "interview_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="interview date"
                    ),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="application number",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
                (
                    "position_applied_for",
                    models.ForeignKey(
                        limit_choices_to={
                            "role_type__in": [
                                "super_admin",
                                "admin",
                                "principal",
                                "department_head",
                                "counselor",
                                "teacher",
                                "accountant",
                                "librarian",
                                "driver",
                                "support",
                                "transport_manager",
                                "hostel_warden",
                            ],
                            "status": "active",
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.role",
                        verbose_name="position applied for",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_staff_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Staff Application",
                "verbose_name_plural": "Staff Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="last name"),
                ),
                ("date_of_birth", models.DateField(verbose_name="date of birth")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(max_length=100, verbose_name="nationality"),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="email address"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="phone number")),
                ("address", models.TextField(verbose_name="address")),
                ("city", models.CharField(max_length=100, verbose_name="city")),
                (
                    "state",
                    models.CharField(max_length=100, verbose_name="state/province"),
                ),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="postal code"),
                ),
                ("country", models.CharField(max_length=100, verbose_name="country")),
                (
                    "grade_applying_for",
                    models.CharField(
                        choices=[
                            ("preschool", "Preschool"),
                            ("kindergarten", "Kindergarten"),
                            ("grade_1", "Grade 1"),
                            ("grade_2", "Grade 2"),
                            ("grade_3", "Grade 3"),
                            ("grade_4", "Grade 4"),
                            ("grade_5", "Grade 5"),
                            ("grade_6", "Grade 6"),
                            ("grade_7", "Grade 7"),
                            ("grade_8", "Grade 8"),
                            ("grade_9", "Grade 9"),
                            ("grade_10", "Grade 10"),
                            ("grade_11", "Grade 11"),
                            ("grade_12", "Grade 12"),
                        ],
                        max_length=20,
                        verbose_name="grade applying for",
                    ),
                ),
                (
                    "previous_school",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="previous school"
                    ),
                ),
                (
                    "previous_grade",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="previous grade"
                    ),
                ),
                (
                    "academic_achievements",
                    models.TextField(blank=True, verbose_name="academic achievements"),
                ),
                (
                    "parent_first_name",
                    models.CharField(
                        max_length=100, verbose_name="parent's first name"
                    ),
                ),
                (
                    "parent_last_name",
                    models.CharField(max_length=100, verbose_name="parent's last name"),
                ),
                (
                    "parent_email",
                    models.EmailField(max_length=254, verbose_name="parent's email"),
                ),
                (
                    "parent_phone",
                    models.CharField(max_length=20, verbose_name="parent's phone"),
                ),
                (
                    "parent_relationship",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("guardian", "Guardian"),
                            ("sibling", "Sibling"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="relationship to student",
                    ),
                ),
                (
                    "birth_certificate",
                    models.FileField(
                        blank=True,
                        help_text="Upload birth certificate (PDF, JPG, PNG)",
                        upload_to="student_applications/birth_certificates/%Y/%m/%d/",
                        verbose_name="birth certificate",
                    ),
                ),
                (
                    "previous_school_transcript",
                    models.FileField(
                        blank=True,
                        help_text="Upload academic transcript from previous school (PDF)",
                        upload_to="student_applications/transcripts/%Y/%m/%d/",
                        verbose_name="previous school transcript",
                    ),
                ),
                (
                    "recommendation_letter",
                    models.FileField(
                        blank=True,
                        help_text="Upload recommendation letter (PDF, DOC, DOCX)",
                        upload_to="student_applications/recommendations/%Y/%m/%d/",
                        verbose_name="recommendation letter",
                    ),
                ),
                (
                    "medical_report",
                    models.FileField(
                        blank=True,
                        help_text="Upload medical report if applicable (PDF)",
                        upload_to="student_applications/medical_reports/%Y/%m/%d/",
                        verbose_name="medical report",
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="medical conditions"),
                ),
                (
                    "special_needs",
                    models.TextField(blank=True, verbose_name="special needs"),
                ),
                (
                    "extracurricular_interests",
                    models.TextField(
                        blank=True, verbose_name="extracurricular interests"
                    ),
                ),
                (
                    "application_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="application status",
                    ),
                ),
                (
                    "application_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="application date"
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="reviewed at"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(blank=True, verbose_name="review notes"),
                ),
                (
                    "application_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        unique=True,
                        verbose_name="application number",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_student_applications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="reviewed by",
                    ),
                ),
                (
                    "user_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="student_application",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user account",
                    ),
                ),
            ],
            options={
                "verbose_name": "Student Application",
                "verbose_name_plural": "Student Applications",
                "ordering": ["-application_date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="emergency contact"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="date of birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                        verbose_name="gender",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="nationality"
                    ),
                ),
                (
                    "identification_number",
                    models.CharField(
                        blank=True,
                        help_text="National ID, Passport number, etc.",
                        max_length=50,
                        verbose_name="identification number",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        help_text="Profile picture (recommended size: 200x200 pixels)",
                        null=True,
                        upload_to="profiles/%Y/%m/%d/",
                        verbose_name="profile picture",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for staff members",
                        max_length=20,
                        null=True,
                        unique=True,
                        verbose_name="employee ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, verbose_name="biography")),
                ("website", models.URLField(blank=True, verbose_name="website")),
                ("facebook", models.URLField(blank=True, verbose_name="facebook")),
                ("twitter", models.URLField(blank=True, verbose_name="twitter")),
                ("linkedin", models.URLField(blank=True, verbose_name="linkedin")),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="SMS notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "last_profile_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="last profile update"
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Designates the primary role for this user",
                        verbose_name="is primary role",
                    ),
                ),
                (
                    "context_id",
                    models.CharField(
                        blank=True,
                        help_text="Role context identifier (e.g., class_id for teachers)",
                        max_length=100,
                        verbose_name="context ID",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="users.role",
                        verbose_name="role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "ordering": ["-is_primary", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assigned", "Role Assigned"),
                            ("removed", "Role Removed"),
                            ("set_primary", "Set as Primary"),
                            ("set_secondary", "Set as Secondary"),
                        ],
                        max_length=15,
                        verbose_name="action type",
                    ),
                ),
                (
                    "details",
                    models.TextField(
                        blank=True,
                        help_text="Additional context about the change",
                        verbose_name="details",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="performed_role_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="performed by",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_activities",
                        to="users.role",
                        verbose_name="affected role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_activities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="affected user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Activity",
                "verbose_name_plural": "User Role Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="session key"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP address")),
                ("user_agent", models.TextField(blank=True, verbose_name="user agent")),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="last activity"),
                ),
                ("expires_at", models.DateTimeField(verbose_name="expires at")),
                (
                    "institution",
                    models.ForeignKey(
                        help_text="Institution this record belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_records",
                        to="core.institution",
                        verbose_name="institution",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Session",
                "verbose_name_plural": "User Sessions",
                "ordering": ["-last_activity"],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["email", "status"], name="users_user_email_785dfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["is_active", "is_verified"],
                name="users_user_is_acti_d093de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["last_login"], name="users_user_last_lo_5f84ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "created_at"], name="users_login_user_id_0a4ab0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["ip_address", "created_at"],
                name="users_login_ip_addr_a63c26_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudentrelationship",
            index=models.Index(
                fields=["parent", "is_primary_contact"],
                name="users_paren_parent__680a73_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="parentstudentrelationship",
            index=models.Index(
                fields=["student", "relationship_type"],
                name="users_paren_student_97a445_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="parentstudentrelationship",
            unique_together={("parent", "student", "relationship_type")},
        ),
        migrations.AddIndex(
            model_name="passwordhistory",
            index=models.Index(
                fields=["user", "created_at"], name="users_passw_user_id_053982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffapplication",
            index=models.Index(
                fields=["application_status", "application_date"],
                name="users_staff_applica_3318ab_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="staffapplication",
            index=models.Index(fields=["email"], name="users_staff_email_a2fa4a_idx"),
        ),
        migrations.AddIndex(
            model_name="staffapplication",
            index=models.Index(
                fields=["application_number"], name="users_staff_applica_e8ad85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staffapplication",
            index=models.Index(
                fields=["position_applied_for"], name="users_staff_positio_03a0c5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentapplication",
            index=models.Index(
                fields=["application_status", "application_date"],
                name="users_stude_applica_0911c8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentapplication",
            index=models.Index(fields=["email"], name="users_stude_email_3159e0_idx"),
        ),
        migrations.AddIndex(
            model_name="studentapplication",
            index=models.Index(
                fields=["application_number"], name="users_stude_applica_f72d2c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["user", "status"], name="users_userp_user_id_d76e9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["identification_number"], name="users_userp_identif_1bd48a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["user", "is_primary"], name="users_userr_user_id_acb348_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(fields=["role"], name="users_userr_role_id_fcacec_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="userrole",
            unique_together={("user", "role", "context_id")},
        ),
        migrations.AddIndex(
            model_name="userroleactivity",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="users_userr_action__ebacb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userroleactivity",
            index=models.Index(
                fields=["user", "created_at"], name="users_userr_user_id_98b8d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleactivity",
            index=models.Index(
                fields=["role", "created_at"], name="users_userr_role_id_7e5b02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleactivity",
            index=models.Index(
                fields=["performed_by", "created_at"],
                name="users_userr_perform_3af372_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["user", "expires_at"], name="users_users_user_id_3581cd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersession",
            index=models.Index(
                fields=["session_key"], name="users_users_session_70af4d_idx"
            ),
        ),
    ]
