# Generated by Django 5.2.7 on 2026-02-17 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, db_index=True, help_text='Optional username that can be used for login in addition to email', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
