# Generated by Django 5.2.7 on 2025-12-10 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark"), ("auto", "Auto")],
                default="dark",
                help_text="Preferred theme for the interface",
                max_length=10,
                verbose_name="theme",
            ),
        ),
    ]
