# Generated by Django 4.2.17 on 2026-02-20 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="staffapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="staffapplication",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="nationality"
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="date of birth"),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                max_length=20,
                verbose_name="gender",
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="nationality",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="nationality"
            ),
        ),
    ]
