# Generated by Django 4.2.17 on 2026-02-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_staffapplication_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffapplication",
            name="highest_qualification",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="highest qualification"
            ),
        ),
        migrations.AlterField(
            model_name="staffapplication",
            name="year_graduated",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="year graduated"
            ),
        ),
    ]
