# Generated by Django 6.0 on 2025-12-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        ("core", "0002_initial"),
        ("support", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="caseattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_attachments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="uploaded by",
            ),
        ),
        migrations.AddField(
            model_name="caseparticipant",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="caseparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_participations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="caseupdate",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="caseupdate",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_updates",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="contactsubmission",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_contacts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="resolved by",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="faqs",
                to="support.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="helpcenterarticle",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="support.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="helpcenterarticle",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="legaldocument",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resources",
                to="support.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                related_name="assigned_cases",
                through="support.CaseParticipant",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned to",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="support_cases",
                to="support.category",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="escalated_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="escalated_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="escalated to",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="reported_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reported_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reported by",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_cases",
                to=settings.AUTH_USER_MODEL,
                verbose_name="resolved by",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="support_cases",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="caseupdate",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="updates",
                to="support.supportcase",
                verbose_name="case",
            ),
        ),
        migrations.AddField(
            model_name="caseparticipant",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="support.supportcase",
                verbose_name="case",
            ),
        ),
        migrations.AddField(
            model_name="caseattachment",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="support.supportcase",
                verbose_name="case",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="supportcase",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="support_cases",
                to="support.tag",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="resources",
                to="support.tag",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="helpcenterarticle",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="support.tag",
                verbose_name="tags",
            ),
        ),
        migrations.AddField(
            model_name="faq",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="faqs", to="support.tag", verbose_name="tags"
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["is_resolved", "created_at"],
                name="support_con_is_reso_e24642_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="contactsubmission",
            index=models.Index(
                fields=["priority", "is_resolved"],
                name="support_con_priorit_e5d235_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="legaldocument",
            index=models.Index(
                fields=["document_type", "is_active"],
                name="support_leg_documen_2b7480_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="caseupdate",
            index=models.Index(
                fields=["case", "created_at"], name="support_cas_case_id_5d691d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseupdate",
            index=models.Index(
                fields=["user", "created_at"], name="support_cas_user_id_62ed0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseupdate",
            index=models.Index(
                fields=["update_type", "created_at"],
                name="support_cas_update__400b82_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["case", "role"], name="support_cas_case_id_58726e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseparticipant",
            index=models.Index(
                fields=["user", "is_active"], name="support_cas_user_id_d84b7d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="caseparticipant",
            unique_together={("case", "user")},
        ),
        migrations.AddIndex(
            model_name="caseattachment",
            index=models.Index(
                fields=["case", "created_at"], name="support_cas_case_id_e3c35c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="caseattachment",
            index=models.Index(
                fields=["uploaded_by", "created_at"],
                name="support_cas_uploade_724423_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["student", "status"], name="support_sup_student_cb2ce9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["case_type", "priority"], name="support_sup_case_ty_a5ad07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["status", "priority"], name="support_sup_status_f650af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["reported_by", "created_at"],
                name="support_sup_reporte_1e8df3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supportcase",
            index=models.Index(
                fields=["case_number"], name="support_sup_case_nu_172974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["resource_type", "is_published"],
                name="support_res_resourc_b93d99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(
                fields=["category", "is_published"],
                name="support_res_categor_83c798_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="helpcenterarticle",
            index=models.Index(
                fields=["article_category", "is_published"],
                name="support_hel_article_a0783c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="helpcenterarticle",
            index=models.Index(
                fields=["category", "is_published"],
                name="support_hel_categor_ebd045_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(
                fields=["category", "is_published"],
                name="support_faq_categor_761aac_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="faq",
            index=models.Index(
                fields=["order", "is_published"], name="support_faq_order_0830cb_idx"
            ),
        ),
    ]
