# Generated by Django 6.0 on 2025-12-12 23:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="notified at"
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="acknowledged at"
                    ),
                ),
                (
                    "acknowledgment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("web", "Web Interface"),
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("app", "Mobile App"),
                        ],
                        max_length=20,
                        verbose_name="acknowledgment method",
                    ),
                ),
                (
                    "response_notes",
                    models.TextField(blank=True, verbose_name="response notes"),
                ),
            ],
            options={
                "verbose_name": "Alert Recipient",
                "verbose_name_plural": "Alert Recipients",
            },
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name="title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="content",
                    ),
                ),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General Announcement"),
                            ("academic", "Academic Announcement"),
                            ("exam", "Exam Related"),
                            ("fee", "Fee Related"),
                            ("holiday", "Holiday Announcement"),
                            ("event", "Event Announcement"),
                            ("urgent", "Urgent Notice"),
                            ("maintenance", "System Maintenance"),
                        ],
                        default="general",
                        max_length=20,
                        verbose_name="announcement type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority level",
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All Users"),
                            ("students", "Students Only"),
                            ("parents", "Parents Only"),
                            ("teachers", "Teachers Only"),
                            ("staff", "Staff Only"),
                            ("admin", "Administrators Only"),
                            ("specific", "Specific Users"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="target audience",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="is published"),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="published at"
                    ),
                ),
                (
                    "schedule_publish",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="schedule publish"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "is_pinned",
                    models.BooleanField(default=False, verbose_name="is pinned"),
                ),
                (
                    "pin_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="pin until"
                    ),
                ),
                (
                    "banner_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="announcements/banners/",
                        verbose_name="banner image",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="communication/attachments/%Y/%m/%d/",
                        verbose_name="attachments",
                    ),
                ),
            ],
            options={
                "verbose_name": "Announcement",
                "verbose_name_plural": "Announcements",
                "ordering": ["-is_pinned", "-published_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("content", models.TextField()),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("image", "Image"),
                            ("system", "System Message"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True, null=True, upload_to="chat_attachments/%Y/%m/%d/"
                    ),
                ),
                ("is_edited", models.BooleanField(default=False)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatParticipant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                ("is_muted", models.BooleanField(default=False)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("member", "Member"),
                            ("admin", "Admin"),
                            ("moderator", "Moderator"),
                        ],
                        default="member",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Participant",
                "verbose_name_plural": "Chat Participants",
                "ordering": ["joined_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("group", "Group Chat"),
                            ("class", "Class Discussion"),
                            ("announcement", "Announcement Channel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chat Room",
                "verbose_name_plural": "Chat Rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="template name"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("system", "System Email"),
                            ("notification", "Notification Email"),
                            ("marketing", "Marketing Email"),
                            ("alert", "Alert Email"),
                        ],
                        default="system",
                        max_length=20,
                        verbose_name="template type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(max_length=200, verbose_name="email subject"),
                ),
                (
                    "body_html",
                    models.TextField(
                        help_text="HTML content for the email", verbose_name="HTML body"
                    ),
                ),
                (
                    "body_text",
                    models.TextField(
                        help_text="Plain text version of the email",
                        verbose_name="text body",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="en", max_length=10, verbose_name="language"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Available variables for this template in JSON format",
                        verbose_name="template variables",
                    ),
                ),
            ],
            options={
                "verbose_name": "Email Template",
                "verbose_name_plural": "Email Templates",
                "ordering": ["name", "language"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="alert title")),
                ("description", models.TextField(verbose_name="alert description")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Emergency"),
                            ("medical", "Medical Emergency"),
                            ("security", "Security Threat"),
                            ("weather", "Severe Weather"),
                            ("infrastructure", "Infrastructure Failure"),
                            ("health", "Health Crisis"),
                            ("other", "Other Emergency"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="alert type",
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("low", "Low - Informational"),
                            ("medium", "Medium - Action Required"),
                            ("high", "High - Immediate Action"),
                            ("critical", "Critical - Evacuation Required"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="alert level",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="alert status",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                (
                    "affected_areas",
                    models.TextField(blank=True, verbose_name="affected areas"),
                ),
                (
                    "evacuation_required",
                    models.BooleanField(
                        default=False, verbose_name="evacuation required"
                    ),
                ),
                (
                    "evacuation_location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="evacuation location"
                    ),
                ),
                (
                    "alert_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="alert time"),
                ),
                (
                    "resolved_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="resolved time"
                    ),
                ),
                (
                    "estimated_resolution",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="estimated resolution"
                    ),
                ),
                (
                    "response_actions",
                    models.TextField(blank=True, verbose_name="response actions"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="contact phone"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "alert_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="emergency_alerts/images/",
                        verbose_name="alert image",
                    ),
                ),
                (
                    "attachments",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="emergency_alerts/attachments/",
                        verbose_name="attachments",
                    ),
                ),
                (
                    "notification_sent",
                    models.BooleanField(
                        default=False, verbose_name="notification sent"
                    ),
                ),
                (
                    "notification_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="notification count"
                    ),
                ),
                (
                    "acknowledgment_required",
                    models.BooleanField(
                        default=True, verbose_name="acknowledgment required"
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Alert",
                "verbose_name_plural": "Emergency Alerts",
                "ordering": ["-alert_time"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyProtocol",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="protocol name"),
                ),
                (
                    "protocol_type",
                    models.CharField(
                        choices=[
                            ("fire", "Fire Emergency Protocol"),
                            ("medical", "Medical Emergency Protocol"),
                            ("security", "Security Threat Protocol"),
                            ("weather", "Severe Weather Protocol"),
                            ("infrastructure", "Infrastructure Failure Protocol"),
                            ("health", "Health Crisis Protocol"),
                            ("evacuation", "Evacuation Protocol"),
                        ],
                        max_length=20,
                        verbose_name="protocol type",
                    ),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "steps",
                    models.JSONField(default=list, verbose_name="response steps"),
                ),
                (
                    "contact_roles",
                    models.JSONField(default=dict, verbose_name="contact roles"),
                ),
                (
                    "resources_required",
                    models.JSONField(default=dict, verbose_name="resources required"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "alert_template",
                    models.TextField(blank=True, verbose_name="alert message template"),
                ),
                (
                    "email_template",
                    models.TextField(blank=True, verbose_name="email template"),
                ),
                (
                    "sms_template",
                    models.TextField(blank=True, verbose_name="SMS template"),
                ),
            ],
            options={
                "verbose_name": "Emergency Protocol",
                "verbose_name_plural": "Emergency Protocols",
                "ordering": ["protocol_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                        verbose_name="subject",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(1)],
                        verbose_name="content",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("direct", "Direct Message"),
                            ("group", "Group Message"),
                            ("system", "System Message"),
                        ],
                        default="direct",
                        max_length=20,
                        verbose_name="message type",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "is_important",
                    models.BooleanField(default=False, verbose_name="is important"),
                ),
                (
                    "requires_confirmation",
                    models.BooleanField(
                        default=False, verbose_name="requires confirmation"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageConfirmation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="confirmed at"
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Confirmation",
                "verbose_name_plural": "Message Confirmations",
            },
        ),
        migrations.CreateModel(
            name="MessageRecipient",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Message Recipient",
                "verbose_name_plural": "Message Recipients",
            },
        ),
        migrations.CreateModel(
            name="NoticeBoard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="board name")),
                (
                    "board_type",
                    models.CharField(
                        choices=[
                            ("main", "Main Notice Board"),
                            ("staff", "Staff Notice Board"),
                            ("student", "Student Notice Board"),
                            ("parent", "Parent Notice Board"),
                            ("event", "Event Notice Board"),
                        ],
                        default="main",
                        max_length=20,
                        verbose_name="board type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="location"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=30,
                        help_text="How often the notice board refreshes in seconds",
                        verbose_name="refresh interval in seconds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice Board",
                "verbose_name_plural": "Notice Boards",
                "ordering": ["board_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="NoticeBoardItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "start_display",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="start display"
                    ),
                ),
                (
                    "end_display",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="end display"
                    ),
                ),
                (
                    "display_duration",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="How long this announcement displays on the board",
                        verbose_name="display duration in seconds",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notice Board Item",
                "verbose_name_plural": "Notice Board Items",
                "ordering": ["display_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "enable_realtime",
                    models.BooleanField(
                        default=True, verbose_name="enable real-time notifications"
                    ),
                ),
                (
                    "message_notifications",
                    models.BooleanField(
                        default=True, verbose_name="message notifications"
                    ),
                ),
                (
                    "assignment_notifications",
                    models.BooleanField(
                        default=True, verbose_name="assignment notifications"
                    ),
                ),
                (
                    "grade_notifications",
                    models.BooleanField(
                        default=True, verbose_name="grade notifications"
                    ),
                ),
                (
                    "announcement_notifications",
                    models.BooleanField(
                        default=True, verbose_name="announcement notifications"
                    ),
                ),
                (
                    "event_notifications",
                    models.BooleanField(
                        default=True, verbose_name="event notifications"
                    ),
                ),
                (
                    "alert_notifications",
                    models.BooleanField(
                        default=True, verbose_name="alert notifications"
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True, verbose_name="email notifications"
                    ),
                ),
                (
                    "push_notifications",
                    models.BooleanField(
                        default=True, verbose_name="push notifications"
                    ),
                ),
                (
                    "sms_notifications",
                    models.BooleanField(
                        default=False, verbose_name="SMS notifications"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False, verbose_name="quiet hours enabled"
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        blank=True, null=True, verbose_name="quiet hours start"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(
                        blank=True, null=True, verbose_name="quiet hours end"
                    ),
                ),
                (
                    "sound_enabled",
                    models.BooleanField(default=True, verbose_name="sound enabled"),
                ),
                (
                    "sound_volume",
                    models.PositiveIntegerField(
                        default=50,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="sound volume",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("email", "Email Template"),
                            ("push", "Push Notification Template"),
                            ("sms", "SMS Template"),
                            ("in_app", "In-App Template"),
                        ],
                        max_length=20,
                        verbose_name="template type",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="subject (for email)"
                    ),
                ),
                ("body", models.TextField(verbose_name="body template")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "variables",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Available variables for template substitution",
                        verbose_name="template variables",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Template",
                "verbose_name_plural": "Notification Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RealTimeNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("message", "New Message"),
                            ("assignment", "Assignment Due"),
                            ("grade", "Grade Posted"),
                            ("announcement", "Announcement"),
                            ("event", "School Event"),
                            ("alert", "System Alert"),
                            ("reminder", "Reminder"),
                            ("achievement", "Achievement Unlocked"),
                            ("warning", "Academic Warning"),
                            ("meeting", "Meeting Scheduled"),
                        ],
                        max_length=20,
                        verbose_name="notification type",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                ("is_read", models.BooleanField(default=False, verbose_name="is read")),
                (
                    "read_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="read at"),
                ),
                ("object_id", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "email_sent",
                    models.BooleanField(default=False, verbose_name="email sent"),
                ),
                (
                    "push_sent",
                    models.BooleanField(
                        default=False, verbose_name="push notification sent"
                    ),
                ),
                (
                    "sms_sent",
                    models.BooleanField(default=False, verbose_name="SMS sent"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="priority",
                    ),
                ),
                (
                    "scheduled_for",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled for"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "action_url",
                    models.URLField(blank=True, null=True, verbose_name="action URL"),
                ),
                (
                    "action_text",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="action text"
                    ),
                ),
            ],
            options={
                "verbose_name": "Real-time Notification",
                "verbose_name_plural": "Real-time Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SentEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "recipient_email",
                    models.EmailField(max_length=254, verbose_name="recipient email"),
                ),
                ("subject", models.CharField(max_length=200, verbose_name="subject")),
                ("body_html", models.TextField(verbose_name="HTML body")),
                ("body_text", models.TextField(verbose_name="text body")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sent at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "opened_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="opened at"
                    ),
                ),
                (
                    "click_count",
                    models.PositiveIntegerField(default=0, verbose_name="click count"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="message ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent Email",
                "verbose_name_plural": "Sent Emails",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SentSMS",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=20, verbose_name="recipient phone"),
                ),
                ("content", models.CharField(max_length=160, verbose_name="content")),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="sent at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="delivered at"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=6,
                        null=True,
                        verbose_name="cost",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="message ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sent SMS",
                "verbose_name_plural": "Sent SMS",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="SMSTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="template name"),
                ),
                (
                    "content",
                    models.TextField(
                        max_length=160,
                        validators=[django.core.validators.MaxLengthValidator(160)],
                        verbose_name="content",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
                (
                    "variables",
                    models.JSONField(
                        default=dict,
                        help_text="Available variables for this template",
                        verbose_name="template variables",
                    ),
                ),
            ],
            options={
                "verbose_name": "SMS Template",
                "verbose_name_plural": "SMS Templates",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Typing Indicator",
                "verbose_name_plural": "Typing Indicators",
                "ordering": ["-timestamp"],
            },
        ),
    ]
