# Generated by Django 5.2.7 on 2025-11-07 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_initial"),
        ("communication", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="alertrecipient",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="author",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="specific_classes",
            field=models.ManyToManyField(
                blank=True,
                related_name="announcements",
                to="academics.class",
                verbose_name="specific classes",
            ),
        ),
        migrations.AddField(
            model_name="announcement",
            name="specific_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="targeted_announcements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="specific users",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="read_by",
            field=models.ManyToManyField(
                blank=True, related_name="read_messages", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="replies",
                to="communication.chatmessage",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_participation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="academic_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.class",
                verbose_name="academic class",
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="admin_chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="members",
            field=models.ManyToManyField(
                related_name="chat_rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="chatroom",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AddField(
            model_name="chatparticipant",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="communication.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="communication.chatroom",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplate",
            unique_together={("name", "language")},
        ),
        migrations.AddField(
            model_name="emergencyalert",
            name="initiated_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="initiated_emergency_alerts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="initiated by",
            ),
        ),
        migrations.AddField(
            model_name="alertrecipient",
            name="alert",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipients",
                to="communication.emergencyalert",
                verbose_name="emergency alert",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyprotocol",
            index=models.Index(
                fields=["protocol_type", "is_active"],
                name="communicati_protoco_b39c51_idx",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="attachments",
            field=models.ManyToManyField(
                blank=True,
                related_name="messages",
                to="academics.fileattachment",
                verbose_name="attachments",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="parent_message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="communication.message",
                verbose_name="parent message",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="sender",
            ),
        ),
        migrations.AddField(
            model_name="messageconfirmation",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="communication.message",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="messageconfirmation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="confirmed_by",
            field=models.ManyToManyField(
                related_name="confirmed_messages",
                through="communication.MessageConfirmation",
                to=settings.AUTH_USER_MODEL,
                verbose_name="confirmed by",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipient_status",
                to="communication.message",
                verbose_name="message",
            ),
        ),
        migrations.AddField(
            model_name="messagerecipient",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="message_status",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="recipients",
            field=models.ManyToManyField(
                related_name="received_messages",
                through="communication.MessageRecipient",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipients",
            ),
        ),
        migrations.AddField(
            model_name="noticeboard",
            name="allowed_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="accessible_notice_boards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="allowed users",
            ),
        ),
        migrations.AddField(
            model_name="noticeboarditem",
            name="announcement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="communication.announcement",
                verbose_name="announcement",
            ),
        ),
        migrations.AddField(
            model_name="noticeboarditem",
            name="notice_board",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="communication.noticeboard",
                verbose_name="notice board",
            ),
        ),
        migrations.AddField(
            model_name="noticeboard",
            name="announcements",
            field=models.ManyToManyField(
                related_name="notice_boards",
                through="communication.NoticeBoardItem",
                to="communication.announcement",
                verbose_name="announcements",
            ),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddField(
            model_name="realtimenotification",
            name="content_object",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realtime_notifications",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="realtimenotification",
            name="content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="realtimenotification",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="realtime_notifications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient",
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_emails",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient user",
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to=settings.AUTH_USER_MODEL,
                verbose_name="sender",
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_emails",
                to="communication.emailtemplate",
                verbose_name="template",
            ),
        ),
        migrations.AddField(
            model_name="sentsms",
            name="recipient_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="received_sms",
                to=settings.AUTH_USER_MODEL,
                verbose_name="recipient user",
            ),
        ),
        migrations.AddField(
            model_name="sentsms",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_sms",
                to="communication.smstemplate",
                verbose_name="template",
            ),
        ),
        migrations.AddField(
            model_name="typingindicator",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_indicators",
                to="communication.chatroom",
            ),
        ),
        migrations.AddField(
            model_name="typingindicator",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="typing_in",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["announcement_type", "is_published"],
                name="communicati_announc_899047_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["target_audience", "status"],
                name="communicati_target__0577ef_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["schedule_publish", "is_published"],
                name="communicati_schedul_5c9185_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="announcement",
            index=models.Index(
                fields=["expires_at", "status"], name="communicati_expires_b453cb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="chatparticipant",
            unique_together={("room", "user")},
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["room", "created_at"], name="communicati_room_id_565731_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["sender", "created_at"], name="communicati_sender__c35a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["alert_type", "status"], name="communicati_alert_t_b47994_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["alert_level", "status"], name="communicati_alert_l_43c305_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyalert",
            index=models.Index(
                fields=["status", "alert_time"], name="communicati_status_a6a201_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecipient",
            index=models.Index(
                fields=["alert", "acknowledged_at"],
                name="communicati_alert_i_26228c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="alertrecipient",
            index=models.Index(
                fields=["recipient", "notified_at"],
                name="communicati_recipie_f549f4_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="alertrecipient",
            unique_together={("alert", "recipient")},
        ),
        migrations.AlterUniqueTogether(
            name="messageconfirmation",
            unique_together={("message", "user")},
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["recipient", "read_at"], name="communicati_recipie_4404c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messagerecipient",
            index=models.Index(
                fields=["message", "recipient"], name="communicati_message_a285c1_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messagerecipient",
            unique_together={("message", "recipient")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "created_at"], name="communicati_sender__9b3871_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["message_type", "status"], name="communicati_message_cf4a14_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["is_important", "created_at"],
                name="communicati_is_impo_cb3b8c_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="noticeboarditem",
            unique_together={("notice_board", "announcement")},
        ),
        migrations.AddIndex(
            model_name="noticeboard",
            index=models.Index(
                fields=["board_type", "is_active"],
                name="communicati_board_t_cbaa63_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimenotification",
            index=models.Index(
                fields=["recipient", "is_read", "created_at"],
                name="communicati_recipie_6eeb4b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimenotification",
            index=models.Index(
                fields=["notification_type", "created_at"],
                name="communicati_notific_fa3cb5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="realtimenotification",
            index=models.Index(
                fields=["priority", "created_at"], name="communicati_priorit_12d9e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimenotification",
            index=models.Index(
                fields=["scheduled_for"], name="communicati_schedul_dad13c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="realtimenotification",
            index=models.Index(
                fields=["expires_at"], name="communicati_expires_797caa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentemail",
            index=models.Index(
                fields=["recipient_email", "sent_at"],
                name="communicati_recipie_771f7c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sentemail",
            index=models.Index(
                fields=["sent_at", "status"], name="communicati_sent_at_75a11f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentemail",
            index=models.Index(
                fields=["template", "sent_at"], name="communicati_templat_674930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sentsms",
            index=models.Index(
                fields=["recipient_phone", "sent_at"],
                name="communicati_recipie_03715b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sentsms",
            index=models.Index(
                fields=["sent_at", "status"], name="communicati_sent_at_496ed4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="typingindicator",
            unique_together={("room", "user")},
        ),
    ]
