# Generated by Django 5.2.7 on 2025-11-07 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("manual_override", "Manual Override"),
                            ("system_correction", "System Correction"),
                            ("makeup_class", "Makeup Class"),
                            ("special_event", "Special Event"),
                        ],
                        max_length=20,
                        verbose_name="exception type",
                    ),
                ),
                (
                    "original_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("holiday", "Holiday"),
                            ("leave", "On Leave"),
                            ("sick", "Sick Leave"),
                            ("excused", "Excused Absence"),
                        ],
                        max_length=20,
                        verbose_name="original status",
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("holiday", "Holiday"),
                            ("leave", "On Leave"),
                            ("sick", "Sick Leave"),
                            ("excused", "Excused Absence"),
                        ],
                        max_length=20,
                        verbose_name="new status",
                    ),
                ),
                ("reason", models.TextField(verbose_name="reason for exception")),
                (
                    "effective_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="effective date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Exception",
                "verbose_name_plural": "Attendance Exceptions",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="session name")),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("morning", "Morning Session"),
                            ("afternoon", "Afternoon Session"),
                            ("full_day", "Full Day"),
                            ("period", "Period Wise"),
                        ],
                        default="full_day",
                        max_length=20,
                        verbose_name="session type",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="start time")),
                ("end_time", models.TimeField(verbose_name="end time")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Attendance Session",
                "verbose_name_plural": "Attendance Sessions",
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceSummary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("month", models.PositiveIntegerField(verbose_name="month")),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                (
                    "total_school_days",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total school days"
                    ),
                ),
                (
                    "days_present",
                    models.PositiveIntegerField(default=0, verbose_name="days present"),
                ),
                (
                    "days_absent",
                    models.PositiveIntegerField(default=0, verbose_name="days absent"),
                ),
                (
                    "days_late",
                    models.PositiveIntegerField(default=0, verbose_name="days late"),
                ),
                (
                    "days_half_day",
                    models.PositiveIntegerField(
                        default=0, verbose_name="days half day"
                    ),
                ),
                (
                    "days_on_leave",
                    models.PositiveIntegerField(
                        default=0, verbose_name="days on leave"
                    ),
                ),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=5,
                        verbose_name="attendance percentage",
                    ),
                ),
                (
                    "consecutive_absences",
                    models.PositiveIntegerField(
                        default=0, verbose_name="consecutive absences"
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Summary",
                "verbose_name_plural": "Attendance Summaries",
            },
        ),
        migrations.CreateModel(
            name="BulkAttendanceSession",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="session name")),
                ("date", models.DateField(verbose_name="date")),
                (
                    "total_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total students"
                    ),
                ),
                (
                    "marked_students",
                    models.PositiveIntegerField(
                        default=0, verbose_name="marked students"
                    ),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="is completed"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk Attendance Session",
                "verbose_name_plural": "Bulk Attendance Sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("date", models.DateField(db_index=True, verbose_name="date")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("absent", "Absent"),
                            ("late", "Late"),
                            ("half_day", "Half Day"),
                            ("holiday", "Holiday"),
                            ("leave", "On Leave"),
                            ("sick", "Sick Leave"),
                            ("excused", "Excused Absence"),
                        ],
                        default="absent",
                        max_length=20,
                        verbose_name="attendance status",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="check in time"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="check out time"
                    ),
                ),
                (
                    "total_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total hours attended",
                        max_digits=4,
                        null=True,
                        verbose_name="total hours",
                    ),
                ),
                ("is_late", models.BooleanField(default=False, verbose_name="is late")),
                (
                    "late_minutes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="late minutes"
                    ),
                ),
                ("remarks", models.TextField(blank=True, verbose_name="remarks")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP address"
                    ),
                ),
                (
                    "device_info",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="device information"
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Attendance",
                "verbose_name_plural": "Daily Attendances",
                "ordering": ["-date", "student"],
            },
        ),
        migrations.CreateModel(
            name="LeaveApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "start_date",
                    models.DateField(db_index=True, verbose_name="start date"),
                ),
                ("end_date", models.DateField(db_index=True, verbose_name="end date")),
                ("total_days", models.PositiveIntegerField(verbose_name="total days")),
                ("reason", models.TextField(verbose_name="reason for leave")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="leave status",
                    ),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="approved at"
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, verbose_name="rejection reason"),
                ),
            ],
            options={
                "verbose_name": "Leave Application",
                "verbose_name_plural": "Leave Applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="leave type name"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="leave code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "max_days_per_year",
                    models.PositiveIntegerField(
                        default=30, verbose_name="maximum days per year"
                    ),
                ),
                (
                    "requires_approval",
                    models.BooleanField(default=True, verbose_name="requires approval"),
                ),
                (
                    "is_paid",
                    models.BooleanField(default=True, verbose_name="is paid leave"),
                ),
                (
                    "allowed_for_students",
                    models.BooleanField(
                        default=True, verbose_name="allowed for students"
                    ),
                ),
                (
                    "allowed_for_teachers",
                    models.BooleanField(
                        default=True, verbose_name="allowed for teachers"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#007bff", max_length=7, verbose_name="color code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Leave Type",
                "verbose_name_plural": "Leave Types",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PeriodAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "period_number",
                    models.PositiveIntegerField(verbose_name="period number"),
                ),
                (
                    "period_start_time",
                    models.TimeField(verbose_name="period start time"),
                ),
                ("period_end_time", models.TimeField(verbose_name="period end time")),
                (
                    "is_present",
                    models.BooleanField(default=False, verbose_name="is present"),
                ),
                (
                    "teacher_remarks",
                    models.TextField(blank=True, verbose_name="teacher remarks"),
                ),
            ],
            options={
                "verbose_name": "Period Attendance",
                "verbose_name_plural": "Period Attendances",
                "ordering": ["daily_attendance", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "school_start_time",
                    models.TimeField(
                        default="08:00:00", verbose_name="school start time"
                    ),
                ),
                (
                    "school_end_time",
                    models.TimeField(
                        default="14:00:00", verbose_name="school end time"
                    ),
                ),
                (
                    "late_threshold_minutes",
                    models.PositiveIntegerField(
                        default=15,
                        help_text="Minutes after start time considered as late",
                        verbose_name="late threshold (minutes)",
                    ),
                ),
                (
                    "half_day_threshold_hours",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Minimum hours required for half day attendance",
                        verbose_name="half day threshold (hours)",
                    ),
                ),
                (
                    "auto_mark_absent_after_days",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Automatically mark absent if no attendance recorded after N days",
                        verbose_name="auto mark absent after days",
                    ),
                ),
                (
                    "enable_biometric",
                    models.BooleanField(
                        default=False, verbose_name="enable biometric integration"
                    ),
                ),
                (
                    "enable_geo_fencing",
                    models.BooleanField(
                        default=False, verbose_name="enable geo-fencing"
                    ),
                ),
                (
                    "notify_parents_on_absence",
                    models.BooleanField(
                        default=True, verbose_name="notify parents on absence"
                    ),
                ),
                (
                    "notify_after_consecutive_absences",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Send notification after N consecutive absences",
                        verbose_name="notify after consecutive absences",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_configs",
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Configuration",
                "verbose_name_plural": "Attendance Configurations",
            },
        ),
    ]
