# Generated by Django 6.0 on 2025-12-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        ("attendance", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendanceexception",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_attendance_exceptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_sessions",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="attendancesummary",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_summaries",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="bulkattendancesession",
            name="attendance_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_sessions",
                to="attendance.attendancesession",
                verbose_name="attendance session",
            ),
        ),
        migrations.AddField(
            model_name="bulkattendancesession",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_attendance_sessions",
                to="academics.class",
                verbose_name="class",
            ),
        ),
        migrations.AddField(
            model_name="bulkattendancesession",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="bulkattendancesession",
            name="marked_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulk_attendance_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marked by",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="attendance_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendances",
                to="attendance.attendancesession",
                verbose_name="attendance session",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marked by",
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendances",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="attendanceexception",
            name="daily_attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exceptions",
                to="attendance.dailyattendance",
                verbose_name="daily attendance",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="applicant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leave_applications",
                to=settings.AUTH_USER_MODEL,
                verbose_name="applicant",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_leaves",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="supporting_documents",
            field=models.ManyToManyField(
                blank=True,
                related_name="leave_applications",
                to="academics.fileattachment",
                verbose_name="supporting documents",
            ),
        ),
        migrations.AddField(
            model_name="leavetype",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="leaveapplication",
            name="leave_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="attendance.leavetype",
                verbose_name="leave type",
            ),
        ),
        migrations.AddField(
            model_name="periodattendance",
            name="daily_attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_attendances",
                to="attendance.dailyattendance",
                verbose_name="daily attendance",
            ),
        ),
        migrations.AddField(
            model_name="periodattendance",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="periodattendance",
            name="marked_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_period_attendances",
                to=settings.AUTH_USER_MODEL,
                verbose_name="marked by",
            ),
        ),
        migrations.AddField(
            model_name="periodattendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_attendances",
                to="academics.subject",
                verbose_name="subject",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendanceconfig",
            unique_together={("academic_session",)},
        ),
        migrations.AlterUniqueTogether(
            name="attendancesession",
            unique_together={("name", "academic_session")},
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["student", "academic_session"],
                name="attendance__student_e57954_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["attendance_percentage"], name="attendance__attenda_fca6c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendancesummary",
            index=models.Index(
                fields=["month", "year"], name="attendance__month_00dc4d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendancesummary",
            unique_together={("student", "academic_session", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["date", "status"], name="attendance__date_a41095_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["student", "date"], name="attendance__student_ed8b4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["status", "date"], name="attendance__status_fa1a7e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyattendance",
            unique_together={("student", "date", "attendance_session")},
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["applicant", "status"], name="attendance__applica_177c94_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["start_date", "end_date"], name="attendance__start_d_d531b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="leaveapplication",
            index=models.Index(
                fields=["status", "created_at"], name="attendance__status_efc579_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="periodattendance",
            index=models.Index(
                fields=["daily_attendance", "is_present"],
                name="attendance__daily_a_41f1da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="periodattendance",
            index=models.Index(
                fields=["subject", "is_present"], name="attendance__subject_3c6612_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="periodattendance",
            unique_together={("daily_attendance", "period_number")},
        ),
    ]
