# Generated by Django 6.0 on 2025-12-14 13:32

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticsCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "cache_key",
                    models.CharField(
                        db_index=True,
                        max_length=255,
                        unique=True,
                        verbose_name="cache key",
                    ),
                ),
                ("data", models.JSONField(verbose_name="cached data")),
                (
                    "data_source",
                    models.CharField(max_length=200, verbose_name="data source"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(db_index=True, verbose_name="expires at"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(auto_now=True, verbose_name="last accessed"),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(default=0, verbose_name="access count"),
                ),
                (
                    "size_bytes",
                    models.PositiveIntegerField(verbose_name="size in bytes"),
                ),
            ],
            options={
                "verbose_name": "Analytics Cache",
                "verbose_name_plural": "Analytics Cache",
                "ordering": ["-last_accessed"],
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="dashboard name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "dashboard_type",
                    models.CharField(
                        choices=[
                            ("system", "System Default"),
                            ("user", "User Custom"),
                            ("role", "Role Specific"),
                        ],
                        default="user",
                        max_length=20,
                        verbose_name="dashboard type",
                    ),
                ),
                (
                    "layout_config",
                    models.JSONField(default=dict, verbose_name="layout configuration"),
                ),
                (
                    "widget_config",
                    models.JSONField(default=dict, verbose_name="widget configuration"),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        default=False, verbose_name="is default dashboard"
                    ),
                ),
                (
                    "refresh_interval",
                    models.PositiveIntegerField(
                        default=15,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(1440),
                        ],
                        verbose_name="refresh interval in minutes",
                    ),
                ),
                (
                    "access_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="access roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DataExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="export name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=200, verbose_name="data source"),
                ),
                (
                    "filters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="export filters"
                    ),
                ),
                (
                    "columns",
                    models.JSONField(
                        blank=True, default=list, verbose_name="selected columns"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                            ("pdf", "PDF"),
                        ],
                        default="excel",
                        max_length=10,
                        verbose_name="export format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="export status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="exports/%Y/%m/%d/",
                        verbose_name="export file",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="file size in bytes"
                    ),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="record count"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="started at"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed at"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="error message"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Export",
                "verbose_name_plural": "Data Exports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KPI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="KPI name")),
                ("code", models.SlugField(unique=True, verbose_name="KPI code")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("financial", "Financial"),
                            ("operational", "Operational"),
                            ("student", "Student Performance"),
                            ("staff", "Staff Performance"),
                            ("system", "System Usage"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("number", "Number"),
                            ("currency", "Currency"),
                            ("duration", "Duration"),
                            ("ratio", "Ratio"),
                        ],
                        default="number",
                        max_length=20,
                        verbose_name="value type",
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="target value",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="minimum value",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="maximum value",
                    ),
                ),
                (
                    "calculation_query",
                    models.TextField(blank=True, verbose_name="calculation query"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=200, verbose_name="data source"),
                ),
                (
                    "refresh_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("hourly", "Hourly"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                        ],
                        default="daily",
                        max_length=20,
                        verbose_name="refresh frequency",
                    ),
                ),
                (
                    "is_trending",
                    models.BooleanField(default=True, verbose_name="show trending"),
                ),
                (
                    "display_format",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="display format"
                    ),
                ),
            ],
            options={
                "verbose_name": "Key Performance Indicator",
                "verbose_name_plural": "Key Performance Indicators",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="KPIMeasurement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(db_index=True, verbose_name="measured at"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="measured value"
                    ),
                ),
                (
                    "previous_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="previous value",
                    ),
                ),
                (
                    "change_percentage",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="change percentage",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="measurement metadata"
                    ),
                ),
            ],
            options={
                "verbose_name": "KPI Measurement",
                "verbose_name_plural": "KPI Measurements",
                "ordering": ["-measured_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="report name")),
                (
                    "parameters",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="report parameters"
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("excel", "Excel"),
                            ("csv", "CSV"),
                            ("json", "JSON"),
                        ],
                        default="html",
                        max_length=10,
                        verbose_name="report format",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="report status",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="report file",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="report data"
                    ),
                ),
                (
                    "summary",
                    models.TextField(blank=True, verbose_name="report summary"),
                ),
                (
                    "generation_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="generation started at"
                    ),
                ),
                (
                    "generation_completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="generation completed at"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="expires at"
                    ),
                ),
                (
                    "access_count",
                    models.PositiveIntegerField(default=0, verbose_name="access count"),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last accessed at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report",
                "verbose_name_plural": "Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReportType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="report type name"),
                ),
                ("code", models.SlugField(unique=True, verbose_name="report code")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("financial", "Financial"),
                            ("attendance", "Attendance"),
                            ("library", "Library"),
                            ("transport", "Transport"),
                            ("staff", "Staff"),
                            ("student", "Student"),
                            ("system", "System"),
                        ],
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=200, verbose_name="data source"),
                ),
                (
                    "is_standard",
                    models.BooleanField(
                        default=True, verbose_name="is standard report"
                    ),
                ),
                (
                    "parameters_schema",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="parameters schema"
                    ),
                ),
                (
                    "refresh_frequency",
                    models.CharField(
                        choices=[
                            ("realtime", "Real-time"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                            ("manual", "Manual"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="refresh frequency",
                    ),
                ),
                (
                    "access_roles",
                    models.JSONField(
                        blank=True, default=list, verbose_name="access roles"
                    ),
                ),
            ],
            options={
                "verbose_name": "Report Type",
                "verbose_name_plural": "Report Types",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrendAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="analysis name"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "data_source",
                    models.CharField(max_length=200, verbose_name="data source"),
                ),
                (
                    "analysis_period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        default="monthly",
                        max_length=20,
                        verbose_name="analysis period",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "trend_direction",
                    models.CharField(
                        choices=[
                            ("upward", "Upward"),
                            ("downward", "Downward"),
                            ("stable", "Stable"),
                            ("volatile", "Volatile"),
                        ],
                        default="stable",
                        max_length=20,
                        verbose_name="trend direction",
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="confidence score",
                    ),
                ),
                (
                    "key_findings",
                    models.JSONField(
                        blank=True, default=list, verbose_name="key findings"
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True, default=list, verbose_name="recommendations"
                    ),
                ),
                (
                    "data_points",
                    models.JSONField(
                        blank=True, default=list, verbose_name="data points"
                    ),
                ),
                (
                    "generated_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="generated at"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trend Analysis",
                "verbose_name_plural": "Trend Analyses",
                "ordering": ["-generated_at"],
            },
        ),
    ]
