# Generated by Django 6.0 on 2025-12-12 23:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        ("analytics", "0002_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dashboards",
                to=settings.AUTH_USER_MODEL,
                verbose_name="owner",
            ),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_exports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requested by",
            ),
        ),
        migrations.AddField(
            model_name="kpi",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="kpimeasurement",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kpi_measurements",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="kpimeasurement",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="kpimeasurement",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurements",
                to="analytics.kpi",
                verbose_name="KPI",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="analytics_reports",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="analytics_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="reporttype",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="report_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="analytics.reporttype",
                verbose_name="report type",
            ),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trend_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="generated by",
            ),
        ),
        migrations.AddField(
            model_name="trendanalysis",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticscache",
            index=models.Index(
                fields=["cache_key", "expires_at"],
                name="analytics_a_cache_k_0d5319_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="analyticscache",
            index=models.Index(
                fields=["expires_at", "status"], name="analytics_a_expires_0eab02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["owner", "is_default"], name="analytics_d_owner_i_e4f3df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dashboard",
            index=models.Index(
                fields=["dashboard_type", "status"],
                name="analytics_d_dashboa_e18658_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dashboard",
            unique_together={("owner", "name")},
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(
                fields=["requested_by", "status"], name="analytics_d_request_6057dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataexport",
            index=models.Index(
                fields=["status", "created_at"], name="analytics_d_status_2bce5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(
                fields=["category", "status"], name="analytics_k_categor_686135_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpi",
            index=models.Index(
                fields=["code", "refresh_frequency"], name="analytics_k_code_895ce5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpimeasurement",
            index=models.Index(
                fields=["kpi", "measured_at"], name="analytics_k_kpi_id_934391_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="kpimeasurement",
            index=models.Index(
                fields=["academic_session", "measured_at"],
                name="analytics_k_academi_5fff28_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="kpimeasurement",
            unique_together={("kpi", "measured_at")},
        ),
        migrations.AddIndex(
            model_name="reporttype",
            index=models.Index(
                fields=["category", "is_standard"],
                name="analytics_r_categor_58b260_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttype",
            index=models.Index(
                fields=["code", "status"], name="analytics_r_code_9f95fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "academic_session"],
                name="analytics_r_report__264723_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "created_at"], name="analytics_r_status_3e008b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["generated_by", "created_at"],
                name="analytics_r_generat_c4eaba_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="trendanalysis",
            index=models.Index(
                fields=["start_date", "end_date"], name="analytics_t_start_d_ae8bab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trendanalysis",
            index=models.Index(
                fields=["trend_direction", "confidence_score"],
                name="analytics_t_trend_d_fa48d0_idx",
            ),
        ),
    ]
