# Generated by Django 4.2.17 on 2026-02-18 19:38

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "bed_number",
                    models.CharField(max_length=10, verbose_name="bed number"),
                ),
                (
                    "bed_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Bed"),
                            ("bunk", "Bunk Bed"),
                            ("double", "Double Bed"),
                            ("cot", "Cot"),
                        ],
                        default="single",
                        max_length=20,
                        verbose_name="bed type",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                (
                    "features",
                    models.TextField(
                        blank=True,
                        help_text="Study table, cupboard, etc.",
                        verbose_name="bed features",
                    ),
                ),
                (
                    "last_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="last maintenance date"
                    ),
                ),
                (
                    "next_maintenance_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="next maintenance date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed",
                "verbose_name_plural": "Beds",
                "ordering": ["room", "bed_number"],
            },
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "address_line_1",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 1"
                    ),
                ),
                (
                    "address_line_2",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="address line 2"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, verbose_name="city"),
                ),
                (
                    "state",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="state/province"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="postal code"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="country"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="phone number"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="mobile number"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="emergency contact"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="emergency phone"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="hostel name")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="hostel code"
                    ),
                ),
                (
                    "hostel_type",
                    models.CharField(
                        choices=[
                            ("boys", "Boys Hostel"),
                            ("girls", "Girls Hostel"),
                            ("coed", "Co-educational"),
                            ("staff", "Staff Quarters"),
                            ("guest", "Guest House"),
                        ],
                        default="boys",
                        max_length=20,
                        verbose_name="hostel type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("deluxe", "Deluxe"),
                            ("premium", "Premium"),
                            ("economy", "Economy"),
                        ],
                        default="standard",
                        max_length=20,
                        verbose_name="hostel category",
                    ),
                ),
                (
                    "total_floors",
                    models.PositiveIntegerField(default=1, verbose_name="total floors"),
                ),
                (
                    "total_rooms",
                    models.PositiveIntegerField(default=0, verbose_name="total rooms"),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="total capacity"
                    ),
                ),
                (
                    "current_occupancy",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current occupancy"
                    ),
                ),
                (
                    "monthly_rent",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="monthly rent",
                    ),
                ),
                (
                    "security_deposit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="security deposit",
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of amenities (WiFi, Laundry, AC, etc.)",
                        verbose_name="amenities",
                    ),
                ),
                ("rules", models.TextField(blank=True, verbose_name="hostel rules")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Hostel",
                "verbose_name_plural": "Hostels",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("allocation_date", models.DateField(verbose_name="allocation date")),
                (
                    "expected_departure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="expected departure date"
                    ),
                ),
                (
                    "actual_departure_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="actual departure date"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                            ("transferred", "Transferred"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="allocation status",
                    ),
                ),
                (
                    "rent_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="monthly rent"
                    ),
                ),
                (
                    "security_deposit_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="security deposit paid",
                    ),
                ),
                (
                    "deposit_refunded",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="deposit refunded",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(blank=True, verbose_name="special requirements"),
                ),
                (
                    "medical_information",
                    models.TextField(blank=True, verbose_name="medical information"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="allocation notes"),
                ),
            ],
            options={
                "verbose_name": "Hostel Allocation",
                "verbose_name_plural": "Hostel Allocations",
                "ordering": ["-allocation_date", "student"],
            },
        ),
        migrations.CreateModel(
            name="HostelFee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "month",
                    models.PositiveIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                        verbose_name="month",
                    ),
                ),
                ("year", models.PositiveIntegerField(verbose_name="year")),
                ("due_date", models.DateField(verbose_name="due date")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="paid amount",
                    ),
                ),
                (
                    "paid_date",
                    models.DateField(blank=True, null=True, verbose_name="paid date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                            ("partial", "Partial Payment"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="fee status",
                    ),
                ),
                (
                    "late_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="late fee",
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="discount",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="Cash, Card, Bank Transfer, etc.",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction ID"
                    ),
                ),
                (
                    "receipt_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="receipt number"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "Hostel Fee",
                "verbose_name_plural": "Hostel Fees",
                "ordering": ["-year", "-month", "allocation"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="item name")),
                ("category", models.CharField(max_length=100, verbose_name="category")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="serial number"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, verbose_name="quantity"),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("in_use", "In Use"),
                            ("under_maintenance", "Under Maintenance"),
                            ("discarded", "Discarded"),
                        ],
                        default="available",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchase date"
                    ),
                ),
                (
                    "purchase_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="purchase cost",
                    ),
                ),
                (
                    "warranty_expiry",
                    models.DateField(
                        blank=True, null=True, verbose_name="warranty expiry"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "Inventory Item",
                "verbose_name_plural": "Inventory Items",
                "ordering": ["hostel", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="MaintenanceRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="issue title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                        verbose_name="priority",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="estimated cost",
                    ),
                ),
                (
                    "actual_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="actual cost",
                    ),
                ),
                (
                    "requested_date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="requested date"
                    ),
                ),
                (
                    "scheduled_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="scheduled date"
                    ),
                ),
                (
                    "completed_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="completed date"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
            ],
            options={
                "verbose_name": "Maintenance Request",
                "verbose_name_plural": "Maintenance Requests",
                "ordering": ["-requested_date", "priority"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "room_number",
                    models.CharField(max_length=20, verbose_name="room number"),
                ),
                (
                    "floor",
                    models.PositiveIntegerField(default=1, verbose_name="floor number"),
                ),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("single", "Single Occupancy"),
                            ("double", "Double Occupancy"),
                            ("triple", "Triple Occupancy"),
                            ("quad", "Four Occupancy"),
                            ("dormitory", "Dormitory"),
                        ],
                        default="double",
                        max_length=20,
                        verbose_name="room type",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(default=2, verbose_name="capacity"),
                ),
                (
                    "current_occupancy",
                    models.PositiveIntegerField(
                        default=0, verbose_name="current occupancy"
                    ),
                ),
                (
                    "rent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Leave blank to use hostel default rent",
                        max_digits=10,
                        null=True,
                        verbose_name="monthly rent",
                    ),
                ),
                (
                    "amenities",
                    models.TextField(
                        blank=True,
                        help_text="Room-specific amenities",
                        verbose_name="room amenities",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="is available"),
                ),
                (
                    "maintenance_required",
                    models.BooleanField(
                        default=False, verbose_name="maintenance required"
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(blank=True, verbose_name="maintenance notes"),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
                "ordering": ["hostel", "floor", "room_number"],
            },
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "visitor_name",
                    models.CharField(max_length=100, verbose_name="visitor name"),
                ),
                (
                    "visitor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="visitor phone"
                    ),
                ),
                (
                    "visitor_id_type",
                    models.CharField(blank=True, max_length=50, verbose_name="ID type"),
                ),
                (
                    "visitor_id_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="ID number"
                    ),
                ),
                (
                    "is_parent_guardian",
                    models.BooleanField(
                        default=False, verbose_name="is parent/guardian"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("meeting", "Meeting"),
                            ("delivery", "Delivery"),
                            ("maintenance", "Maintenance"),
                            ("official", "Official Work"),
                            ("parent_visit", "Parent Visit"),
                            ("other", "Other"),
                        ],
                        default="meeting",
                        max_length=20,
                        verbose_name="visit purpose",
                    ),
                ),
                (
                    "check_in_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="check in time"
                    ),
                ),
                (
                    "check_out_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="check out time"
                    ),
                ),
                (
                    "items_carried",
                    models.TextField(blank=True, verbose_name="items carried"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "photo_id_verified",
                    models.BooleanField(
                        default=False, verbose_name="photo ID verified"
                    ),
                ),
                (
                    "allowed_items_only",
                    models.BooleanField(
                        default=True, verbose_name="allowed items only"
                    ),
                ),
            ],
            options={
                "verbose_name": "Visitor Log",
                "verbose_name_plural": "Visitor Logs",
                "ordering": ["-check_in_time"],
            },
        ),
    ]
