# Generated by Django 6.0 on 2025-12-14 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0003_initial"),
        ("core", "0002_initial"),
        ("hostels", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="hostel",
            name="assistant_warden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assistant_managed_hostels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assistant warden",
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="hostel",
            name="warden",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_hostels",
                to=settings.AUTH_USER_MODEL,
                verbose_name="warden",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostel_allocations",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="allocated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="allocated_beds",
                to=settings.AUTH_USER_MODEL,
                verbose_name="allocated by",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="hostels.bed",
                verbose_name="bed",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="class_enrolled",
            field=models.ForeignKey(
                blank=True,
                help_text="Student's class at time of allocation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hostel_allocations",
                to="academics.class",
                verbose_name="class enrolled",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="emergency_contact",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hostel_emergency_contacts",
                to="academics.parentguardian",
                verbose_name="emergency contact",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="hostelallocation",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="hostel_allocations",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="hostelfee",
            name="allocation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fees",
                to="hostels.hostelallocation",
                verbose_name="hostel allocation",
            ),
        ),
        migrations.AddField(
            model_name="hostelfee",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory",
                to="hostels.hostel",
                verbose_name="hostel",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_maintenance",
                to=settings.AUTH_USER_MODEL,
                verbose_name="assigned to",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="bed",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="maintenance_requests",
                to="hostels.bed",
                verbose_name="bed",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="hostels.hostel",
                verbose_name="hostel",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to=settings.AUTH_USER_MODEL,
                verbose_name="requested by",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="hostels.hostel",
                verbose_name="hostel",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="preferred_class",
            field=models.ForeignKey(
                blank=True,
                help_text="Preferred class for this room allocation",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="preferred_rooms",
                to="academics.class",
                verbose_name="preferred class",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="hostels.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory",
                to="hostels.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="hostels.room",
                verbose_name="room",
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authorized_visits",
                to=settings.AUTH_USER_MODEL,
                verbose_name="authorized by",
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="hostel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitors",
                to="hostels.hostel",
                verbose_name="hostel",
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="parent_guardian",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hostel_visits",
                to="academics.parentguardian",
                verbose_name="parent/guardian",
            ),
        ),
        migrations.AddField(
            model_name="visitorlog",
            name="visiting_student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visitors",
                to="academics.student",
                verbose_name="visiting student",
            ),
        ),
        migrations.AddIndex(
            model_name="hostel",
            index=models.Index(
                fields=["hostel_type", "is_active"],
                name="hostels_hos_hostel__58a081_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostel",
            index=models.Index(
                fields=["category", "status"], name="hostels_hos_categor_ae806e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostel",
            index=models.Index(
                fields=["current_occupancy", "capacity"],
                name="hostels_hos_current_12a040_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["student", "status"], name="hostels_hos_student_93f3b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["bed", "academic_session"], name="hostels_hos_bed_id_abfd51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["allocation_date", "status"],
                name="hostels_hos_allocat_a00233_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["academic_session", "status"],
                name="hostels_hos_academi_041b0f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostelallocation",
            index=models.Index(
                fields=["class_enrolled", "status"],
                name="hostels_hos_class_e_032fa9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="hostelfee",
            index=models.Index(
                fields=["allocation", "status"], name="hostels_hos_allocat_904bd4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelfee",
            index=models.Index(
                fields=["due_date", "status"], name="hostels_hos_due_dat_00a789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelfee",
            index=models.Index(
                fields=["month", "year", "status"], name="hostels_hos_month_17a70b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hostelfee",
            index=models.Index(
                fields=["transaction_id"], name="hostels_hos_transac_32afe5_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="hostelfee",
            unique_together={("allocation", "month", "year")},
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["hostel", "floor"], name="hostels_roo_hostel__064f4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["room_type", "is_available"],
                name="hostels_roo_room_ty_c06bf6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["is_available", "maintenance_required"],
                name="hostels_roo_is_avai_6238d0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="room",
            index=models.Index(
                fields=["preferred_class"], name="hostels_roo_preferr_f62abb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hostel", "room_number")},
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["hostel", "status"], name="hostels_mai_hostel__746e74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["priority", "status"], name="hostels_mai_priorit_014dfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="maintenancerequest",
            index=models.Index(
                fields=["assigned_to", "status"], name="hostels_mai_assigne_208175_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["hostel", "status"], name="hostels_inv_hostel__515b98_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["category", "condition"], name="hostels_inv_categor_590c95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="inventoryitem",
            index=models.Index(
                fields=["status", "condition"], name="hostels_inv_status_8b8a20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(
                fields=["room", "is_available"], name="hostels_bed_room_id_4b91c9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(
                fields=["last_maintenance_date"], name="hostels_bed_last_ma_22ce51_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bed",
            unique_together={("room", "bed_number")},
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["hostel", "check_in_time"],
                name="hostels_vis_hostel__e37265_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["visiting_student", "check_in_time"],
                name="hostels_vis_visitin_ecbe5e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["is_parent_guardian"], name="hostels_vis_is_pare_681060_idx"
            ),
        ),
    ]
