# Generated by Django 6.0 on 2025-12-14 13:32

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityAchievement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "achievement_type",
                    models.CharField(
                        choices=[
                            ("participation", "Participation"),
                            ("performance", "Performance"),
                            ("leadership", "Leadership"),
                            ("team_player", "Team Player"),
                            ("improvement", "Improvement"),
                            ("other", "Other"),
                        ],
                        default="participation",
                        max_length=20,
                        verbose_name="achievement type",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="achievement title"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                ("achievement_date", models.DateField(verbose_name="achievement date")),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="certificate issued"
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="certificate number"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/achievements/",
                        verbose_name="achievement photo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Achievement",
                "verbose_name_plural": "Activity Achievements",
                "ordering": ["-achievement_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityAttendance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                ("session_date", models.DateField(verbose_name="session date")),
                (
                    "is_present",
                    models.BooleanField(default=False, verbose_name="is present"),
                ),
                (
                    "arrival_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="arrival time"
                    ),
                ),
                (
                    "departure_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="departure time"
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notes")),
                (
                    "participation_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Rate participation from 1-5",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="participation rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Attendance",
                "verbose_name_plural": "Activity Attendance",
                "ordering": ["-session_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "budget_type",
                    models.CharField(
                        choices=[("revenue", "Revenue"), ("expense", "Expense")],
                        max_length=20,
                        verbose_name="budget type",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("equipment", "Equipment"),
                            ("venue", "Venue Rental"),
                            ("transport", "Transportation"),
                            ("materials", "Materials/Supplies"),
                            ("staff", "Staff Compensation"),
                            ("marketing", "Marketing/Promotion"),
                            ("fees", "Registration Fees"),
                            ("sponsorship", "Sponsorship"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="category",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "planned_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="planned date"
                    ),
                ),
                (
                    "actual_date",
                    models.DateField(blank=True, null=True, verbose_name="actual date"),
                ),
                (
                    "approval_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="approval date"
                    ),
                ),
                (
                    "receipt",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="activities/budgets/",
                        verbose_name="receipt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Budget",
                "verbose_name_plural": "Activity Budgets",
                "ordering": ["activity", "-planned_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="category name"
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("sports", "Sports"),
                            ("arts", "Arts"),
                            ("clubs", "Clubs"),
                            ("competitions", "Competitions"),
                            ("academic_clubs", "Academic Clubs"),
                            ("cultural", "Cultural"),
                            ("community_service", "Community Service"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="category type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="FontAwesome icon class",
                        max_length=50,
                        verbose_name="icon",
                    ),
                ),
                (
                    "color_code",
                    models.CharField(
                        default="#3498db", max_length=7, verbose_name="color code"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Activity Category",
                "verbose_name_plural": "Activity Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityEnrollment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, verbose_name="enrollment date"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("waitlisted", "Waitlisted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "special_requirements",
                    models.TextField(blank=True, verbose_name="special requirements"),
                ),
                (
                    "emergency_contact",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="emergency contact"
                    ),
                ),
                (
                    "medical_conditions",
                    models.TextField(blank=True, verbose_name="medical conditions"),
                ),
                (
                    "payment_status",
                    models.BooleanField(
                        default=False, verbose_name="payment completed"
                    ),
                ),
                (
                    "payment_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="payment date"
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="transaction ID"
                    ),
                ),
                (
                    "attendance_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="attendance count"
                    ),
                ),
                (
                    "last_attendance",
                    models.DateField(
                        blank=True, null=True, verbose_name="last attendance"
                    ),
                ),
                (
                    "performance_notes",
                    models.TextField(blank=True, verbose_name="performance notes"),
                ),
                (
                    "grade",
                    models.CharField(blank=True, max_length=5, verbose_name="grade"),
                ),
                (
                    "certificate_issued",
                    models.BooleanField(
                        default=False, verbose_name="certificate issued"
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Enrollment",
                "verbose_name_plural": "Activity Enrollments",
                "ordering": ["-enrollment_date"],
            },
        ),
        migrations.CreateModel(
            name="ActivityStaffAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("coordinator", "Coordinator"),
                            ("coach", "Coach"),
                            ("assistant_coach", "Assistant Coach"),
                            ("advisor", "Advisor"),
                            ("volunteer", "Volunteer"),
                        ],
                        default="coach",
                        max_length=20,
                        verbose_name="role",
                    ),
                ),
                (
                    "assigned_date",
                    models.DateField(auto_now_add=True, verbose_name="assigned date"),
                ),
                (
                    "is_primary",
                    models.BooleanField(default=False, verbose_name="is primary"),
                ),
                (
                    "responsibilities",
                    models.TextField(blank=True, verbose_name="responsibilities"),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="hourly rate",
                    ),
                ),
                (
                    "hours_per_week",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=4,
                        null=True,
                        verbose_name="hours per week",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity Staff Assignment",
                "verbose_name_plural": "Activity Staff Assignments",
                "ordering": ["activity", "role"],
            },
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "club_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic"),
                            ("cultural", "Cultural"),
                            ("service", "Service"),
                            ("special_interest", "Special Interest"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="club type",
                    ),
                ),
                (
                    "mission_statement",
                    models.TextField(blank=True, verbose_name="mission statement"),
                ),
                (
                    "meeting_schedule",
                    models.TextField(blank=True, verbose_name="meeting schedule"),
                ),
                (
                    "budget_allocated",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="budget allocated",
                    ),
                ),
                (
                    "resources_needed",
                    models.TextField(blank=True, verbose_name="resources needed"),
                ),
            ],
            options={
                "verbose_name": "Club",
                "verbose_name_plural": "Clubs",
                "ordering": ["activity__title"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="competition title"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "competition_type",
                    models.CharField(
                        choices=[
                            ("tournament", "Tournament"),
                            ("league", "League"),
                            ("championship", "Championship"),
                            ("friendly", "Friendly Match"),
                            ("other", "Other"),
                        ],
                        default="tournament",
                        max_length=20,
                        verbose_name="competition type",
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("school", "School Level"),
                            ("district", "District Level"),
                            ("state", "State Level"),
                            ("national", "National Level"),
                            ("international", "International Level"),
                        ],
                        default="school",
                        max_length=20,
                        verbose_name="competition level",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "registration_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="registration deadline"
                    ),
                ),
                (
                    "max_teams",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum teams"
                    ),
                ),
                (
                    "max_individuals",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum individuals"
                    ),
                ),
                ("rules", models.TextField(verbose_name="rules and regulations")),
                (
                    "format_description",
                    models.TextField(blank=True, verbose_name="format description"),
                ),
                (
                    "scoring_system",
                    models.TextField(blank=True, verbose_name="scoring system"),
                ),
                (
                    "first_prize",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="first prize"
                    ),
                ),
                (
                    "second_prize",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="second prize"
                    ),
                ),
                (
                    "third_prize",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="third prize"
                    ),
                ),
                (
                    "venue",
                    models.CharField(blank=True, max_length=200, verbose_name="venue"),
                ),
                (
                    "contact_person",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact person"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="is active"),
                ),
            ],
            options={
                "verbose_name": "Competition",
                "verbose_name_plural": "Competitions",
                "ordering": ["-start_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="equipment name"),
                ),
                (
                    "equipment_type",
                    models.CharField(
                        choices=[
                            ("sports", "Sports Equipment"),
                            ("arts", "Arts Supplies"),
                            ("electronics", "Electronics"),
                            ("books", "Books/Materials"),
                            ("uniforms", "Uniforms"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="equipment type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "quantity_total",
                    models.PositiveIntegerField(
                        default=1, verbose_name="total quantity"
                    ),
                ),
                (
                    "quantity_available",
                    models.PositiveIntegerField(
                        default=1, verbose_name="available quantity"
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Good"),
                            ("fair", "Fair"),
                            ("poor", "Poor"),
                            ("damaged", "Damaged"),
                        ],
                        default="good",
                        max_length=20,
                        verbose_name="condition",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="purchase price",
                    ),
                ),
                (
                    "purchase_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="purchase date"
                    ),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="supplier"
                    ),
                ),
                (
                    "last_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="last maintenance"
                    ),
                ),
                (
                    "next_maintenance",
                    models.DateField(
                        blank=True, null=True, verbose_name="next maintenance"
                    ),
                ),
                (
                    "maintenance_notes",
                    models.TextField(blank=True, verbose_name="maintenance notes"),
                ),
                (
                    "storage_location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="storage location"
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment",
                "ordering": ["equipment_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="SportsTeam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("pending", "Pending"),
                            ("suspended", "Suspended"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "team_name",
                    models.CharField(max_length=100, verbose_name="team name"),
                ),
                (
                    "team_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("competitive", "Competitive"),
                        ],
                        default="beginner",
                        max_length=20,
                        verbose_name="team level",
                    ),
                ),
                (
                    "max_players",
                    models.PositiveIntegerField(
                        default=15, verbose_name="maximum players"
                    ),
                ),
                (
                    "min_players",
                    models.PositiveIntegerField(
                        default=8, verbose_name="minimum players"
                    ),
                ),
                ("wins", models.PositiveIntegerField(default=0, verbose_name="wins")),
                (
                    "losses",
                    models.PositiveIntegerField(default=0, verbose_name="losses"),
                ),
                ("draws", models.PositiveIntegerField(default=0, verbose_name="draws")),
                (
                    "points",
                    models.PositiveIntegerField(default=0, verbose_name="points"),
                ),
            ],
            options={
                "verbose_name": "Sports Team",
                "verbose_name_plural": "Sports Teams",
                "ordering": ["team_name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="created at"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="updated at"
                    ),
                ),
                (
                    "status_changed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="status changed at"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="is deleted"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="deleted at"
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="activity title"),
                ),
                ("description", models.TextField(verbose_name="description")),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("team", "Team"),
                            ("group", "Group"),
                        ],
                        default="individual",
                        max_length=20,
                        verbose_name="activity type",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("one_time", "One Time"),
                            ("weekly", "Weekly"),
                            ("biweekly", "Bi-weekly"),
                            ("monthly", "Monthly"),
                            ("seasonal", "Seasonal"),
                        ],
                        default="one_time",
                        max_length=20,
                        verbose_name="frequency",
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="maximum participants"
                    ),
                ),
                (
                    "min_participants",
                    models.PositiveIntegerField(
                        default=1, verbose_name="minimum participants"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="end date"),
                ),
                (
                    "start_time",
                    models.TimeField(blank=True, null=True, verbose_name="start time"),
                ),
                (
                    "end_time",
                    models.TimeField(blank=True, null=True, verbose_name="end time"),
                ),
                (
                    "days_of_week",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated days (monday,tuesday,etc.)",
                        max_length=100,
                        verbose_name="days of week",
                    ),
                ),
                (
                    "venue",
                    models.CharField(blank=True, max_length=200, verbose_name="venue"),
                ),
                (
                    "room_number",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="room number"
                    ),
                ),
                (
                    "equipment_needed",
                    models.TextField(blank=True, verbose_name="equipment needed"),
                ),
                (
                    "fee_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="fee amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="USD", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planning",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "prerequisites",
                    models.TextField(blank=True, verbose_name="prerequisites"),
                ),
                (
                    "objectives",
                    models.TextField(blank=True, verbose_name="learning objectives"),
                ),
                (
                    "contact_info",
                    models.TextField(blank=True, verbose_name="contact information"),
                ),
                (
                    "registration_deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="registration deadline"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="activities/images/",
                        verbose_name="activity image",
                    ),
                ),
                (
                    "brochure",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="activities/brochures/",
                        verbose_name="brochure",
                    ),
                ),
                (
                    "academic_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="academics.academicsession",
                        verbose_name="academic session",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "ordering": ["-start_date", "title"],
            },
        ),
    ]
