# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("academics", "0002_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sportsteam",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="sportsteam",
            name="vice_captain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vice_captained_teams",
                to="academics.student",
                verbose_name="vice captain",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="assigned_to_activity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="equipment",
                to="activities.activity",
                verbose_name="assigned to activity",
            ),
        ),
        migrations.AddField(
            model_name="equipment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="competitions",
                to="activities.activity",
                verbose_name="related activity",
            ),
        ),
        migrations.AddField(
            model_name="competition",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="activity",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="club",
                to="activities.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="president",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="presided_clubs",
                to="academics.student",
                verbose_name="president",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="secretary",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secretary_clubs",
                to="academics.student",
                verbose_name="secretary",
            ),
        ),
        migrations.AddField(
            model_name="club",
            name="vice_president",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vice_presided_clubs",
                to="academics.student",
                verbose_name="vice president",
            ),
        ),
        migrations.AddField(
            model_name="activitystaffassignment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_assignments",
                to="activities.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AddField(
            model_name="activitystaffassignment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
    ]
