# Generated by Django 4.2.17 on 2026-02-18 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0002_initial"),
        ("academics", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitystaffassignment",
            name="staff_member",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_assignments",
                to=settings.AUTH_USER_MODEL,
                verbose_name="staff member",
            ),
        ),
        migrations.AddField(
            model_name="activityenrollment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="activities.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AddField(
            model_name="activityenrollment",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="activityenrollment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_enrollments",
                to="academics.student",
                verbose_name="student",
            ),
        ),
        migrations.AddField(
            model_name="activitycategory",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="activitybudget",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="budget_items",
                to="activities.activity",
                verbose_name="activity",
            ),
        ),
        migrations.AddField(
            model_name="activitybudget",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_budget_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="approved by",
            ),
        ),
        migrations.AddField(
            model_name="activitybudget",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="activityattendance",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_records",
                to="activities.activityenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AddField(
            model_name="activityattendance",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="activityachievement",
            name="awarded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="awarded_achievements",
                to=settings.AUTH_USER_MODEL,
                verbose_name="awarded by",
            ),
        ),
        migrations.AddField(
            model_name="activityachievement",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="achievements",
                to="activities.activityenrollment",
                verbose_name="enrollment",
            ),
        ),
        migrations.AddField(
            model_name="activityachievement",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="academic_session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="academics.academicsession",
                verbose_name="academic session",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="activities.activitycategory",
                verbose_name="category",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="coordinator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="coordinated_activities",
                to=settings.AUTH_USER_MODEL,
                verbose_name="coordinator",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="institution",
            field=models.ForeignKey(
                help_text="Institution this record belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_records",
                to="core.institution",
                verbose_name="institution",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["equipment_type", "condition"],
                name="activities__equipme_e34591_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="equipment",
            index=models.Index(
                fields=["assigned_to_activity"], name="activities__assigne_534d1f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["activity", "start_date"], name="activities__activit_bf321f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="competition",
            index=models.Index(
                fields=["competition_type", "level"],
                name="activities__competi_da722f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitystaffassignment",
            index=models.Index(
                fields=["staff_member", "activity"],
                name="activities__staff_m_581ad4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitystaffassignment",
            index=models.Index(
                fields=["activity", "role"], name="activities__activit_6ced64_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activitystaffassignment",
            unique_together={("staff_member", "activity", "role")},
        ),
        migrations.AddIndex(
            model_name="activityenrollment",
            index=models.Index(
                fields=["student", "status"], name="activities__student_d411af_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityenrollment",
            index=models.Index(
                fields=["activity", "status"], name="activities__activit_811c91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activityenrollment",
            index=models.Index(
                fields=["enrollment_date", "status"],
                name="activities__enrollm_0ba1cc_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityenrollment",
            unique_together={("student", "activity")},
        ),
        migrations.AddIndex(
            model_name="activitybudget",
            index=models.Index(
                fields=["activity", "budget_type"],
                name="activities__activit_f20388_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activitybudget",
            index=models.Index(
                fields=["category", "budget_type"],
                name="activities__categor_e95aa6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityattendance",
            index=models.Index(
                fields=["enrollment", "session_date"],
                name="activities__enrollm_652478_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityattendance",
            index=models.Index(
                fields=["session_date", "is_present"],
                name="activities__session_ed2547_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="activityattendance",
            unique_together={("enrollment", "session_date")},
        ),
        migrations.AddIndex(
            model_name="activityachievement",
            index=models.Index(
                fields=["enrollment", "achievement_date"],
                name="activities__enrollm_b5b94a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityachievement",
            index=models.Index(
                fields=["achievement_type", "achievement_date"],
                name="activities__achieve_4fa435_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["category", "status"], name="activities__categor_d7cee1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["start_date", "end_date"], name="activities__start_d_a8febb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["academic_session", "status"],
                name="activities__academi_251aa0_idx",
            ),
        ),
    ]
